### ISSUE TITLE
Randoop does not add elements to generic collections

### ISSUE THREAD

**Issue by hsanchez** [randoop/randoop#105]
@mernst, @bjkeller 

Here is the example class I used to evaluate Randoop 3.0.

```java
import java.util.List;
import java.util.LinkedList;
import java.util.Arrays;

public class SortingExamples {

 public static void main(String... args){
    int[] arr1 = {10,34,2,56,7,67,88,42};
	SortingExamples.selectionSort(arr1);
	
	System.out.println("Selection sort with Integer array");
	for (int i=0;i<arr1.length;i++) {
		System.out.println(arr1[i]);
	}
	
	List<Integer> arr2 = new LinkedList<Integer>(Arrays.asList(34,2,56,88,7,67,10,42));
	SortingExamples.genericSelectionSort(arr2);
	
	System.out.println("Generic selection sort with list of comparables");
	for (int j=0;j<arr2.size();j++) {
		System.out.println(arr2.get(j));
	}
 }

 /**
  * 1. Selection sort for integer arrays, as written in class.
  */
 public static void selectionSort(int[] arr){
   for (int i = 0; i < arr.length - 1; ++i){
     int minIndex = i;
     for (int j = i + 1; j < arr.length; ++j){
       if (arr[j] < arr[minIndex]){
         minIndex = j;
       }
     }

     int temp = arr[i];
     arr[i] = arr[minIndex];
     arr[minIndex] = temp;
   }
 }

 /**
  * 2. (Generic) selection sort for a list of comparables
  */
 public static <T extends Comparable<T>> void genericSelectionSort(List<T> arr){
   for (int i = 0; i < arr.size() - 1; ++i){
     int minIndex = i;
     for (int j = i + 1; j < arr.size(); ++j){
       if (arr.get(j).compareTo(arr.get(minIndex)) < 0){
         minIndex = j;
       }
     }
     // String changed to T
     T temp = arr.get(i);
     arr.set(i, arr.get(minIndex));
     arr.set(minIndex, temp);
   }
 }  
}
```

We used the following Randoop flags:

```
--timelimit=2
--silently-ignore-bad-class-names=true
--testclass=SortingExamples
--oom-exception=INVALID
--junit-output-dir=/path/to/randoop_tests/
```  

## Observations

Using the above settings (and input file), Randoop 3.0 generated 48 test cases (See attached file). 1 test for the generic selection sort method, 1 test for the SortingExamples’s constructor, and 46 tests for the non-generic selection sort method. 

We looked at these test cases and found that **Randoop 3.0 did not add elements to generic collections**. We also observed normal Randoop behavior for the non generic selection sort method: every now and then, it calls the same method over and over again to check if this method can have a side effect.

## The logs

INFO: Generate Randoop tests for:
SortingExamples
java -ea -classpath lib/randoop.jar:and_other_libraries_and_folders randoop.main.Main gentests --junit-output-dir=/path/to/randoop_tests/ --testclass=SortingExamples --silently-ignore-bad-class-names=true --oom-exception=INVALID --timelimit=2

INFO: starting command
policy = sun.security.provider.PolicyFile@2d98a335
PUBLIC MEMBERS=4
Explorer = randoop.generation.ForwardGenerator@deb6432

Progress update: test inputs generated=0, failing inputs=0      (Tue Jun 14 12:28:38 PDT 2016)
Progress update: test inputs generated=874, failing inputs=0      (Tue Jun 14 12:28:40 PDT 2016)
Normal method executions:14974
Exceptional method executions:2

Average method execution time (normal termination):      0.0931
Average method execution time (exceptional termination): 0.219

No error-revealing tests to output

Regression test output:
Regression test count: 48
Writing JUnit tests...

Created file: /path/to/randoop_tests/RegressionTest0.java
Created file: /path/to/randoop_tests/RegressionTest.java
policy = sun.security.provider.PolicyFile@2d98a335
PUBLIC MEMBERS=4
Explorer = randoop.generation.ForwardGenerator@deb6432

Progress update: test inputs generated=0, failing inputs=0      (Tue Jun 14 12:28:38 PDT 2016)
Progress update: test inputs generated=874, failing inputs=0      (Tue Jun 14 12:28:40 PDT 2016)
Normal method executions:14974
Exceptional method executions:2

Average method execution time (normal termination):      0.0931
Average method execution time (exceptional termination): 0.219

No error-revealing tests to output

Regression test output:
Regression test count: 48
Writing JUnit tests...

Created file: /path/to/randoop_tests/RegressionTest0.java
Created file: /path/to/randoop_tests/RegressionTest.java

Process finished with exit code 0

## Randoop FILE

[RegressionTest0.java.txt](https://github.com/randoop/randoop/files/314819/RegressionTest0.java.txt)

**Comment by bjkeller** [comment]
@hsanchez 
Thanks for reporting this.  This is fixed in the current master, and will be included in v3.0.1.
