### ISSUE TITLE
Running Randoop in the IntelliJ debugger fails with java.lang.IllegalArgumentException: Path component should be '/'

### ISSUE THREAD

**Issue by langelescu** [randoop/randoop#1076]
I have cloned tag v4.3.0 of Randoop and have used _./gradlew idea_ to generate the IntelliJ Idea (v22.1.3 Ultimate) project file in Windows 11. I am running Oracle OpenJDK version 1.8_0_211. The repo is placed in C:\Users\lange\source\repos\randoop.

No run/debug configurations existed therefore I created a basic one to validate installation and configuration of the development environment. The idea is to be able to run randoop under Debug mode and step through the program. The configuration looks like so:

![image](https://user-images.githubusercontent.com/20031312/190930415-cd1a128a-60bb-453d-9b96-affb1fdd489d.png)

With this configuration, when running/debugging Randoop, it fails with the message "**java.lang.IllegalArgumentException: Path component should be '/'**". The output from the IntelliJ Idea run trace is:

> Task :Main.main() FAILED
>   Randoop for Java version "4.3.0, branch HEAD, commit b069486, 2022-01-31".
>   
>   Throwable thrown while handling command: java.lang.IllegalArgumentException: Path component should be '/'
>   java.lang.IllegalArgumentException: Path component should be '/'
> 	  at sun.nio.fs.WindowsFileSystemProvider.checkUri(WindowsFileSystemProvider.java:69)
> 	  at sun.nio.fs.WindowsFileSystemProvider.newFileSystem(WindowsFileSystemProvider.java:80)
> 	  at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
> 	  at java.nio.file.FileSystems.newFileSystem(FileSystems.java:276)
> 	  at randoop.main.GenTests.getResourceDirectoryPath(GenTests.java:1320)
> 	  at randoop.main.GenTests.getJDKSpecificationFiles(GenTests.java:1281)
> 	  at randoop.main.GenTests.handle(GenTests.java:301)
> 	  at randoop.main.Main.nonStaticMain(Main.java:71)
> 	  at randoop.main.Main.main(Main.java:31)
> 
>   Randoop failed.
>   No sequences generated.
> 
>   Execution failed for task ':Main.main()'.
>   Process 'command 'C:/Program Files/Java/jdk1.8.0_211/bin/java.exe'' finished with non-zero exit value 1
> 
>   * Try:
>   - Run with --stacktrace option to get the stack trace.
>   - Run with --info or --debug option to get more log output.
>   - Run with --scan to get full insights.

The same thing or behaviour happens if I create an IntelliJ configuration and run it under Linux Ubuntu 22.04 LTS running Java 8 OpenJDK. This makes me think that it's an IDE configuration issue. I am able, however, to run Randoop from the command line:

> **java -cp "./randoop-all-4.3.0.jar;C:\Users\lange\source\repos\TestBenchmark" randoop.main.Main gentests --testclass=FizzBuzz**
> Randoop for Java version "4.3.0, branch HEAD, commit b069486, 2022-01-31".
> 
> Will try to generate tests for 1 classes.
> PUBLIC MEMBERS=5
> Explorer = ForwardGenerator(steps: 0, null steps: 0, num_sequences_generated: 0;
>     allSequences: 0, regresson seqs: 0, error seqs: 0=0=0, invalid seqs: 0, subsumed_sequences: 0, num_failed_output_test: 0;
>     runtimePrimitivesSeen:38)
> 
> Progress update: steps=1, test inputs generated=0, failing inputs=0      (2022-09-18T22:38:06.266Z     29.7M used)
> [...]
> 

I am hoping that you may be able to point me in the right direction with respect to identifying and fixing this error.

**Comment by langelescu** [comment]
I installed a fresh Ubuntu 22.04 environment and I was able to run Randoop without this issue. Closing.

**Comment by mernst** [comment]
Thank you for reporting what fixed your problem.  That is helpful.

Please let us know if you have further difficulties.
