### ISSUE TITLE
NPE in generated RegressionTest

### ISSUE THREAD

**Issue by martinezmatias** [randoop/randoop#109]
A method  X under test creates and  throws an anonymous exception:
.....
  return new IllegalArgumentException() {

            @Override
            public String getMessage() {
                return buildMessage(Locale.US, pattern, arguments);
            }
         ........

Then, the regression test generated by Randoop throws a NPE when it receives the expected exception: The canonical name of the received anonymous exception is null.

.....X()....//Method under test, Randoop expects an exception. It receives an anonymous exception.
 org.junit.Assert.fail("Expected exception of type null"); ///See
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("null")) { ///HERE NPE!
        org.junit.Assert.fail("Expected exception of type null, got " + e.getClass().getCanonicalName());
      }

**Comment by mernst** [comment]
Thanks for the bug report, and I'm sorry you encountered this problem.

Could you please provide a complete reproducible test case?  You can probably do so quickly (even if you have to anonymize or minimize), whereas it will take us time to guess at your code.  Furthermore, if we have your test case, the bug fix will be certain to make Randoop work for you.  Thanks for your help!

**Comment by martinezmatias** [comment]
Hi Michael, 
Thanks for your response.
I send you a small project that includes: 
- The class named "Entity" to test.
- A Randoop Runner: generates the regression test cases for Entity.
- The generated test cases (folder src/test/java) 
Thanks! 
Best regards
Matias
[randoopTest.zip](https://github.com/randoop/randoop/files/337483/randoopTest.zip)
