### ISSUE TITLE
I am facing an issue while writing test cases to a file

### ISSUE THREAD

**Issue by SanketBhave** [randoop/randoop#1095]
<img width="727" alt="Screen Shot 2022-11-19 at 12 34 09 PM" src="https://user-images.githubusercontent.com/22407966/202839138-0cc0c041-038c-41de-9907-65257f7021a2.png">
Thanks for submitting an issue.

Please first search the manual, especially the Troubleshooting section (https://randoop.github.io/randoop/manual/#troubleshooting).  It may already answer your question.

As explained in the instructions for submitting an issue (https://randoop.github.io/randoop/manual/#bug-reporting), include at least the following information.

The version of Randoop, the output of `java -version`, and the operating system version.

The complete commands you ran, so that we can paste them into a command terminal.  Please don't omit any steps, including installing software or setting environment variables.  Please use [troubleshooting options](https://randoop.github.io/randoop/manual/index.html#optiongroup:Logging,-notifications,-and-troubleshooting-Randoop) as appropriate.

A transcript of all the output (as text, not a screenshot).

What you expected to happen instead.  (If Randoop completed but did not output a test that you want, give an example test.)

Files that are used by the commands you ran.

**Comment by mernst** [comment]
You didn't provide any of the information requested for a bug report.
We will investigate your problem if you do so.
