### ISSUE TITLE
Provide A Working Example For --init-routine

### ISSUE THREAD

**Issue by opticyclic** [randoop/randoop#110]
I am trying to generate some tests for code that doesn't initialise fully in the constructor. Randoop generates lots of null pointers in the tests because it doesn't call the init method.

The [manual says](https://randoop.github.io/randoop/manual/index.html#command-line-options):

    Varying the nature of generated tests
    
        --init-routine=string. Specifies initialization routine (class.method)

When I start Randoop with:

     --init-routine=my.package.Viewer.init

I get the error

    ERROR: Can't find init method init: java.lang.NoSuchMethodException: my.package.Viewer.init(int)

How do I specify that my init method takes several parameters?

**Comment by bjkeller** [comment]
I apologize for the lack of documentation about `--init-routine`.  This is an old option that needs to be removed. The method given is actually meant to be an initialization for Randoop and does not allow specifying an init method for a particular class.

If you want to email me directly (or post to https://groups.google.com/forum/#!forum/randoop-discuss), I can help you resolve your initialization difficulties.
