### ISSUE TITLE
Randoop should not filter out all abstract classes

### ISSUE THREAD

**Issue by bjkeller** [randoop/randoop#117]
Randoop filters out abstract classes that are given as input as classes under test.
This is because the class cannot be instantiated with `new`.  However, the class might have static methods that Randoop could call, even to create instances of (subclasses of) the abstract class.

Randoop should not filter out abstract classes.
However, Randoop should never try to call `new` on an abstract class.

OLD ISSUE TEXT FOLLOWS:

Randoop cannot generate abstract classes such as `com.google.common.collect.ImmutableList<E>`, which implements `java.util.Collection<E>` but does not have known non-abstract extensions.  The `com.google.common.ImmutableCollection<E>` classes all provide static methods that allow an object to be created.

**Comment by mernst** [comment]
Is the right solution to have the user provide `ImmutableCollection` as one of the classes under test?  Or should Randoop automatically add `ImmutableCollection` to the classes under test (or at least the classes whose methods are candidates for invocation) whenever the user includes `ImmuatbleList` among the classes under test?

**Comment by bjkeller** [comment]
The actual issue has to do with how collections are constructed, and the fact that these are abstract classes.
