### ISSUE TITLE
java.lang.AssertionError: didn't find types to satisfy bounds on generic

### ISSUE THREAD

**Issue by mausotog** [randoop/randoop#122]
Dear Prof. Ernst and Randoop team, I hope everything is great.
The other very common issue I am running into is the one that reads: "didn't find types to satisfy bounds on generic"
It is also showing in several of bugs detailed in defects4j as detailed before.
For example, if I take the bug called "Math 20" which corresponds to Apache Commons Math. The steps in order to recreate the issue are the following:
-I first clone defects4j from the link above. (I tried attaching the source code, but even compressed it's too big)
-Then checkout this particular bug using the command:
../defects4j/framework/bin/defects4j checkout -p Math -v 20f -w /some/location/in/my/pc/
-I then run randoop. Which can be ran in two ways: With a direct call to Randoop:
java -ea -classpath ../randoop-all-3.0.4.jar:target/classes/ randoop.main.Main gentests --classlist=20.src --timelimit=180 --randomseed=1
(20.src can be found in defects4j/framework/projects/Closure/loaded_classes/126.src)
-Or through defects4j which calls Randoop indirectly:
perl run_randoop.pl -p Math -v 20f -n 1 -o /some/output/folder/ -b 180
(run_randoop.pl can be found in defects4j/framework/bin/run_randoop.pl)

My expectation would be that Randoop creates a test suite out of the checked out code and if it has any issue, it should just skip the test case it is trying to create in that particular moment and continue with the following. But instead, I get the output attached, which causes Randoop to fail and create no test suite at all.

Regards,

Mauricio Soto

[outputMath20.txt](https://github.com/randoop/randoop/files/505620/outputMath20.txt)

**Comment by bjkeller** [comment]
Mauricio,
Thank you for this report.  I have been working through the Randoop failures running on Defects4J. This and several others are fixed in the current working version, and will be included in the next release. (Instead of failing an assertion, the message is logged if logging is turned on.)
Thanks,
Ben
