### ISSUE TITLE
Is there any way to generate test cases for abstract classes with Randoop?

### ISSUE THREAD

**Issue by jose** [randoop/randoop#124]
Hi,

It seems that Randoop is not able to generate test cases for abstract classes. If I have to guess, I would say that Randoop works like that because a Java abstract class is a class which cannot be instantiated, i.e., new instances of an abstract class cannot be created.

I wonder if there is any option/parameter to tell Randoop to generate test cases for an abstract class, by generating test cases for any class (from the classpath) that extends the abstract-class-under-test...

--
Cheers,
Jose

**Comment by mernst** [comment]
Your idea is the right one:  you can supply, on the command line or in a classlist file, the names of the classes that extend the abstract class.
