### ISSUE TITLE
Randoop is generating tests with null input for non premitive data types of my class even though   --forbid-null=true is passed

### ISSUE THREAD

**Issue by Pallav-552** [randoop/randoop#1256]
Thanks for submitting an issue.

Please first search the manual, especially the Troubleshooting section (https://randoop.github.io/randoop/manual/#troubleshooting).  It may already answer your question.

As explained in the instructions for submitting an issue (https://randoop.github.io/randoop/manual/#bug-reporting), include at least the following information.

The version of Randoop, the output of `java -version`, and the operating system version.

The complete commands you ran, so that we can paste them into a command terminal.  Please don't omit any steps, including installing software or setting environment variables.  Please use [troubleshooting options](https://randoop.github.io/randoop/manual/index.html#optiongroup:Logging,-notifications,-and-troubleshooting-Randoop) as appropriate.

A transcript of all the output (as text, not a screenshot).

What you expected to happen instead.  (If Randoop completed but did not output a test that you want, give an example test.)

Files that are used by the commands you ran.

**Comment by mernst** [comment]
This issue is missing necessary information.
