### ISSUE TITLE
Document multiple versions of manual

### ISSUE THREAD

**Issue by mernst** [randoop/randoop#154]
It's confusing that the manual appears twice, both times checked into the version control repository, at randoop/src/docs/manual and randoop/docs/manual.  Both of them need a README pointing at the other.  Also, the READMEs should document regarding which copy of the manual should be edited.  Please make the other version of the manual read-only to prevent accidental editing.

**Comment by bjkeller** [comment]
The directory `randoop/docs` has the name mandated for a GitHub project pages directory.  The naming is unfortunate and I've added my +1 to the feature request to allow the name to be configurable.  Options we have to avoid the confusion are to either go back to using the gh-pages branch, or allowing the files in this directory to be edited (removing the corresponding files in `src/docs`).

I'm going to push the repo in a state with the requested README files. However, the build script hasn't been modified to maintain the README in the project pages directory. A rewrite with careful application of delete and copy tasks are needed in the publishSite task.

The files in the project pages directory are all read-only after publishSite, but the file modes are not preserved by git so will not be there in a fresh clone or (maybe) after a pull.  There were already git-hooks in scripts that reset the file mode, but these scripts were not executable. They are now, which should hopefully help with the read-only problem.

**Comment by mernst** [comment]
The README files have been added.
