### ISSUE TITLE
Change build script so that src/docs/manual files are updated by generated TOC and options documentation

### ISSUE THREAD

**Issue by mernst** [randoop/randoop#155]
Please change these gradle tasks:

  updateUserTOC
  updateDevTOC
  generateOptionsDoc

so that they side-effect the editable version of the manual in randoop/src/docs/manual/.

The current version only updates the versions in build/, which means that the main version that developers edit will get further and further out of date, with incorrect table of contents and option documentation.  This is confusing, and it makes it unnecessarily difficult for developers to read and modify the manual.

Please also ensure that tasks such as validateManual work on the version that gets edited.  Otherwise developers may waste time by clicking on the error message generated by the tool, editing the generated version, and not fix the actual problem.  (Making the generated versions of the manual read-only needs to be done to partially assuage the problem, but that won't help developers to find the version that they do need to edit.)

**Comment by bjkeller** [comment]
I think the `Javadoc` task always uses the destination directory, which is inconsistent with the way that the TOC and Options doclets work.  
These should be rewritten using 
```groovy
doLast {
  project.exec {
     commandLine = 
  }
}
```
to avoid conflicting assumptions.

**Comment by bjkeller** [comment]
fixed by f39f958e5d3ad993b42f933934e4a9b72782fcf4
