### ISSUE TITLE
Eliminate nondeterminism in set of covered methods in Randoop system test suite

### ISSUE THREAD

**Issue by mernst** [randoop/randoop#156]
On at least 4 occasions, I ran
  ./gradlew clean build
twice in a row.  The first time, this test failed:

randoop.main.RandoopSystemTest > runNaiveCollectionsTest FAILED
    java.lang.AssertionError: Excluded methods that are covered:
      java2.util2.TreeSet.last()
        at org.junit.Assert.fail(Assert.java:88)
        at randoop.main.CoverageChecker.checkCoverage(CoverageChecker.java:136)
        at randoop.main.RandoopSystemTest.generateAndTestWithCoverage(RandoopSystemTest.java:876)
        at randoop.main.RandoopSystemTest.runNaiveCollectionsTest(RandoopSystemTest.java:291)

The second time, everything succeeded.

**Comment by bjkeller** [comment]
I need to check that all data structures from which types and sequences are selected is ordered (e.g., not using a `HashSet`), and that the order is consistent between runs.  We already resolved this for operations (at least twice).

**Comment by bjkeller** [comment]
One candidate is `SequenceCollection.sequenceTypes` that, though, created as a `LinkedHashSet<Type>`, may be populated in different order depending on the order in which sequences are created.  However, I think this traces back to `SeedSequences.defaultSeeds()`.

**Comment by bjkeller** [comment]
Changed `Set<Type>` collections in `OperationModel` to use `TreeSet<Type>`.  The order `Type.compareTo` uses the qualified names of types.

**Comment by bjkeller** [comment]
I'm not seeing them, but still getting reports of problems with this.

I looked more closely at `runCollectionsTest`. What I've found:
1. A couple of methods simply cannot be called -- private and not helpers to other methods.
2. Some methods are helpers to other methods, but are not called.
3. Several are called with bad input (null arguments, empty receiver collection)
4. For one, there is no way to create an argument value
5. The rest are simply not called. 

Items 2 and 5 are actual coverage issues.  It is possible to pare down the not-called list by increasing the generation limit.  On my machine, cranking the output limit to 1000 resulted in only one method that was not selected.

**Comment by bjkeller** [comment]
Looked at diffs between runs on my Mac and between the three Travis builds for runNaiveCollectionsTest:
- total operations: 260, all same
- operation selections: 365 on Travis JDK7 and 8, 367 on Mac, 369 on Travis OpenJDK7 including  187 operations
- operations included in tests: 196 selections including 114 operations on Travis, 198 of 113 operations on Mac

There are
- 260 total operations
- 113 common to all platforms
- 73 unselected
- 74 non-included

**Comment by bjkeller** [comment]
After making changes in earlier releases, this problem has not recurred on Travis CI. If you continue to have the problem, please rebase on the current master.
