### ISSUE TITLE
Remove non-compiling tests

### ISSUE THREAD

**Issue by mernst** [randoop/randoop#158]
Randoop sometimes outputs non-compiling tests.  For example, Randoop sometimes makes type mistakes when instantiating complex generics.

These non-compiling tests are Randoop bugs that need to be fixed, but in the meanwhile I suggest that Randoop remove these tests from its output.  This will greatly increase the utility of Randoop to clients:  instead of presenting them with no test suite that compiles, the users will receive a slightly larger, but useful, set of tests.

Such behavior is already built into tools like Defects4J, but it should not have to be.

This should be higher priority than fixing any specific non-compiling tests, because it has a much larger positive impact on

There can be a command-line argument, intended for use by Randoop developers, that would retain these tests in the output.  That would enable Randoop developers to continue to fix non-compiling tests as time permits.

**Comment by bjkeller** [comment]
Added non-compiling test feature in v.3.1.0 (https://github.com/randoop/randoop/commit/ed0f21cabaebde0675005d1816451c5abfbedd78)
