### ISSUE TITLE
--include-if-class-exercised requires javassist to be on the classpath

### ISSUE THREAD

**Issue by rjust** [randoop/randoop#167]
When using the *--include-if-class-exercised* option, Randoop needs to be invoked with a java agent -- this is documented and clear. However, that java agent relies on the javassist library, which has to be on the classpath -- this is not documented.

The manual should clarify this dependency, and a release should either include or reference the javassist.jar library.

**Comment by bjkeller** [comment]
Thanks René, I noticed this the other day with the mapcall agent. We need to be releasing fat jars for both.

**Comment by bjkeller** [comment]
constructed exercised-class jar now includes dependencies. 
fixed by 651ba87aab675a9ee1875a11290e2fc4f09746ae
