### ISSUE TITLE
Seems that Randoop does not support enum type

### ISSUE THREAD

**Issue by GoogleCodeExporter** [randoop/randoop#17]
```
A simple example:

public enum Currency {
   USD, CAD, CNY
}

public class WorldMoney {
  public int convert (int amount, Currency currency) {
    // body omit here
 }
}

The convert(amount, currency) method will never be called by Randoop, due to 
the missing of Currency type.


```

Original issue reported on code.google.com by `saizh...@google.com` on 9 Sep 2010 at 1:58

**Comment by opticyclic** [comment]
Since Google Code is going away soon, I cherry picked this change and made a pull request.
https://github.com/mernst/randoop/pull/56

**Comment by bjkeller** [comment]
Changes complete, tested, committed and pushed.
