### ISSUE TITLE
Cannot find the Java compiler. Check that classpath includes tools.jar

### ISSUE THREAD

**Issue by tuyen** [randoop/randoop#176]
I run randoop with command: 
java -ea -classpath bin;%RANDOOP_JAR% randoop.main.Main gentests --testclass=first.Abc --timelimit=60
The result is error:
Throwable thrown while handling command: java.lang.IllegalStateException: Cannot find the Java compiler. Check that classpath includes tools.jar
java.lang.IllegalStateException: Cannot find the Java compiler. Check that classpath includes tools.jar
        at randoop.compile.SequenceCompiler.<init>(SequenceCompiler.java:54)
        at randoop.test.CompilableTestPredicate.<init>(CompilableTestPredicate.java:51)
        at randoop.main.GenTests.createTestOutputPredicate(GenTests.java:618)
        at randoop.main.GenTests.handle(GenTests.java:393)
        at randoop.main.Main.nonStaticMain(Main.java:62)
        at randoop.main.Main.main(Main.java:26)

Randoop failed.
Last sequence under execution: null

p/s: I have already installed java and the JAVA_HOME is set to C:\Program Files\Java\jdk1.8.0_101 folder and path environment to the bin folder.
I'm using windows 10.
Randoop version: 3.1.2

**Comment by mernst** [comment]
What happens when you put `tools.jar` on the classpath?

**Comment by tuyen** [comment]
I have tried with command:
java -ea -classpath bin;%RANDOOP_JAR%;C:\Progra~1\Java\jdk1.8.0_101\lib\tools.jar randoop.main.Main gentests --testclass=first.Abc --timelimit=60
OR:
java -ea -classpath bin;%RANDOOP_JAR%;%JAVA_HOME%\lib\tools.jar randoop.main.Main gentests --testclass=first.Abc --timelimit=60

But the result still the same :(

**Comment by bjkeller** [comment]
I believe that if you are running java from the JDK and your JAVA_HOME is set correctly, it shouldn't be necessary to add tools.jar explicitly to the class path. So, my suggestions are 
1. Double check that JAVA_HOME is set properly
2. Make sure you are running java from %JAVA_HOME%\bin. 

I'm not a current Windows user, but my understanding is that anytime a path includes spaces, you need to have double quotes around the path. This could include the whole class path or just individual parts.

**Comment by tuyen** [comment]
I have uninstalled the old java installed on Program Files, I install new java to D:\java\
Setting environment variable. All things are checked very closely. But the result still same.
![image](https://cloud.githubusercontent.com/assets/12403480/24665087/894d3912-1986-11e7-9cac-b1c94cd6c872.png)

![image](https://cloud.githubusercontent.com/assets/12403480/24665055/72e64e66-1986-11e7-90c4-9cf956bc1f00.png)
![image](https://cloud.githubusercontent.com/assets/12403480/24665200/da350c38-1986-11e7-8588-09be14f5aeec.png)

**Comment by tuyen** [comment]
Sorry that I have deleted first.ABC file, but it is just a simple class with 1 simple function like:
public String getName(String name){
   if(name.length > 0) return "hello mr. " + name;
return "hello randoop";
}

recently I tested with file uit.se.recsys.App and problem still there. You can take a look at this file instead. (please change the .txt to .java for better code display, cause git not allow upload .java file)
[App.txt](https://github.com/randoop/randoop/files/893750/App.txt)

p/s: I think that problem is inside code of randoop. Inside SequenceCompiler, at this line: ToolProvider.getSystemJavaCompiler(); it can not find a compiler because of some unknown reason,

**Comment by bjkeller** [comment]
It looks to me like you have another Java directory in the PATH at the top of the first image. Can you confirm that does not have a JRE that is getting used instead? In other words, that when you run java it is actually running the one in the JDK.

Once you know for certain that you are running java from the JDK, try putting tools.jar on the path like before.

We appreciate your patience with us. This issue is related to a new feature and we don't have any experience with the kinds of problems that people will have with the configuration.

**Comment by tuyen** [comment]
Thanks @bjkeller, you have point the Java directory in PATH for me. I searched about it and find this article: https://douglascayers.com/2015/05/30/how-to-set-custom-java-path-after-installing-jdk-8/. My problem sovled.
I have change the JAVA_HOME to the **front** of the PATH then it works! (do not add the tools.jar to the classpath)
Thank you all!

**Comment by mernst** [comment]
Great!  Is there some way we could change the Randoop instructions to help other people, or is this purely a Java setup issue?

**Comment by bjkeller** [comment]
I suspect we can improve both the instructions and error message, but, if the linked post is to be believed, ultimately the problem is a Java configuration issue on Windows.

**Comment by tuyen** [comment]
It is exactly the Java configuration issue on Windows, but I think that you should add this problem to Randoop instructions to help others if they meet the same problem. It's wasted me a day to searching on the internet and looking for help to solve the problem.

**Comment by mernst** [comment]
I have improved the manual.  In the future, we could improve the error message too.
Thanks again for the report and the fix.

**Comment by anshul28101997** [comment]
![image](https://user-images.githubusercontent.com/38157270/77597794-d6539200-6ef7-11ea-9fa2-ca6473942051.png)
I have set up the PATH and JAVA_path as shown. The problem still persists. I have gone through all the comments, but cannot figure this out.
