### ISSUE TITLE
--omitmethods should match inherited methods (and documentation should be updated)

### ISSUE THREAD

**Issue by mernst** [randoop/randoop#179]
The `--omitmethods` documentation should indicate that the regex is not anchored -- that is, users may wish to use "^" and "$" in it, and the examples should use those as well.

Another surprise was that I tried to prevent a call

        plume.CountingPrintWriter countingPrintWriter9 = ...
        java.io.PrintWriter printWriter13 = countingPrintWriter9.append(char12);

by using the regex

    plume\\.CountingPrintWriter\\.append

but this did not work.
I had to instead use the regex

    java\\.io\\.PrintWriter\\.append

In the short term, this should be documented.  In the longer term, it would be good to be able to specify not just the method implementation that is dispatched to but also the method that is invoked.

**Comment by bjkeller** [comment]
I think this is one of those cases where the technology is not a good match to how we think of our tasks. In your example, because the method is inherited, without an override, there is no reflection object with a name that matches `plume\\.CountingPrintWriter\\.append`. You might think of it this way, but to work the way you are thinking of it, the regex would have to be decomposed into two parts: the prefix that matches the class name, and the suffix that matches the method name.

I think we should find another way to describe the methods to ignore.

**Comment by mernst** [comment]
The fact that there is a reflection object is an implementation detail.  The user just wants to specify what method should not be called, and should be able to do so.

When you say "we should find another way to describe the methods to ignore":  are you proposing a change to the UI, the specification, or the implementation?

**Comment by bjkeller** [comment]
The UI. Beyond this issue, writing a regex to match multiple methods can be painful.

**Comment by bjkeller** [comment]
I've changed `--omitmethods` so that it can be repeated, accumulating a `List<Pattern>` instead of requiring one.  This, of course, doesn't address any of your points.

I also added notes to the command-line documentation about anchoring and matching the superclass.

**Comment by bjkeller** [comment]
[Implementation note] Current implementation filters the methods of classes under test in the reflection predicate. However, there is no matching `java.lang.reflect.Method` when the omitted method is inherited without override. This means that the test for omission should instead happen when the operations for a class are built.

**Comment by bjkeller** [comment]
Another complication of the current implementation is that `--omitmethods` matches the pattern against the `toString()` value of the method/constructor. This string actually includes access modifiers and return type, so anchoring the working form of the plume-lib example as in 
```
^java\\.io\\.PrintWriter\\.append
```
would not actually match the intended method for which the `toString()` value is
```
public PrintWriter java.io.PrintWriter.append(char)
```

A fix should match against the signature `java.io.PrintWriter.append(char)` or `plume.CountingPrintWriter.append(char)`.

**Comment by bjkeller** [comment]
See PR #189
