### ISSUE TITLE
Randoop does not print confirmation that explains effect of uncompilable sequence filtering

### ISSUE THREAD

**Issue by bjkeller** [randoop/randoop#184]
Anshul Gupta reported running Randoop 3.1.5 on `java.util.Collections` and `java.util.TreeSet` and having no generated tests.

Randoop prints messages about instantiation errors (actually repeatedly for the same methods), but does not provide an explanation that uncompilable tests were generated and filtered.   It should instead provide a count of filtered sequences (providing as much information as possible) and asking for a report.

**Comment by apoorva-sriv** [comment]
I think this issue can be closed since the current version of Randoop (4.2.6) shows
`Uncompilable sequences generated (count: <num>).`

**Comment by mernst** [comment]
Thank you for pointing that out.  I will close the issue.
