### ISSUE TITLE
Gradle task validateSite: Java 8 vs 9 inconsistency

### ISSUE THREAD

**Issue by mernst** [randoop/randoop#203]
This Gradle task tests `isJava9Compatible()` but the else clause has a message about Java 8 rather than Java 9.  I'm not sure which one is desired.

```
task validateSite(type: Exec) {
  description "Run html5validator to find HTML errors in site files (excludes manual and api)"
  if (JavaVersion.current().isJava9Compatible()) {
    environment PATH: "$System.env.PATH"
    commandLine "html5validator", "--root", "docs/", "--ignore", "docs/api"
  } else {
    commandLine "echo", "WARNING: HTML validation of site only run in Java 8+"
  }
}
```

**Comment by bjkeller** [comment]
It should be sufficient to run this in Java 8. But, the validator doesn't approve of the following line that appears in two of the top-level files in the site:

```
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
```

This refers to the Chrome Frame plugin, which apparently has not been supported for quite a while.
