### ISSUE TITLE
Confusing omitmethods documentation

### ISSUE THREAD

**Issue by mernst** [randoop/randoop#206]
This documentation for `--omitmethods` is unclear:

```
   *   <li>If a method is inherited without an override, the pattern must match the superclass
   *       method.
```

Does "the superclass method" mean in the immediate superclass?  What if the superclass also inherits the method?  What are the consequences of "must match" (does Randoop crash if that requirement is violated)?

Also, there may be multiple supertypes that define a method:  for example, both an interface and a superclass.  How are interfaces treated?

I think it's better to have a simple specification, even if the implementation is a bit more complicated, rather than having a complex specification that will confuse and surprise every user.

Here are some example simpler specifications we could consider:
 * The method name is arbitrary; invocations at the given subclass or lower are forbidden.
 * The method must have an implementation in the given class (or else Randoop exits with an error message).

**Comment by bjkeller** [comment]
I believe this is resolved in the `--omitmethods` PR: https://github.com/randoop/randoop/pull/189.
