### ISSUE TITLE
Make Error Prone skip over files in src/testinput

### ISSUE THREAD

**Issue by mernst** [randoop/randoop#208]
In commit fdbc267aaf523d641de5821f20b313b4950005b0, I made improvements suggested by the Error Prone tool.

However, I have not enabled Error Prone.  Error Prone needs to skip over files in `src/testinput/`.  Please adjust the build file to enable Error Prone and to exclude test input files from its checks.

**Comment by bjkeller** [comment]
There is supposed to be an alternate version of the plugin that doesn't do automatic configuration, but it does not seem to be published.  I added an issue on the site.

**Comment by mernst** [comment]
Can you please give a link to the issue?  That way it's easier to check the status.

**Comment by bjkeller** [comment]
Plugin issue: https://github.com/tbroyer/gradle-errorprone-plugin/issues/44
