### ISSUE TITLE
Gradle targets for testing

### ISSUE THREAD

**Issue by mernst** [randoop/randoop#209]
What is the difference between
```./gradlew test systemtest```
and
```./gradlew check```
?

Should the Gradle "test" target be renamed "unittest" for clarity?

The developer manual gives a rather complex command that achieves more thorough checking; why not have a more simply-named target for this, which Travis could also use?  How is it different than the "build" target, and should the "build" target also do all that checking?

It could be cleaner to eliminate the "validateManual" target (or make it an internal, unadvertised target) and have that done every time that `./gradlew manual` is run.  Is run-time cost the reason that this is not done currently?

**Comment by bjkeller** [comment]
`./gradlew check` runs all of the tests and not just `test` and `systemtest`.  The `build` task uses `check`.

The task `test` runs the classes in the default Gradle source set for JUnit tests.  It is not necessarily the case that a test in that source set is a "unit test".  The distinction has more to do with how the tests are run than whether they are unit, integration or system tests.

**Comment by bjkeller** [comment]
I moved the command from `validateManual` into `manual`.

**Comment by bjkeller** [comment]
On Travis, having the different parts of the build done separately allows us to be more precise about when we want more information from Gradle.  Specifically, running `check` with `--info` is helpful when a test fails.

I added a dependency that makes `./gradlew clean build` equivalent to the Travis run, though I think it is useful to document the particular tasks in the developer's manual.

**Comment by mernst** [comment]
Could you update the developer manual?  It still says:

>  Randoop has three kinds of tests:
>  unit tests of Randoop internal classes (under directory <code>src/test</code>),
>  unit tests of Randoop Java agents (under directory <code>src/agenttest</code>), and
>  system tests that run Randoop on input classes.

I'm not sure if this classification is still accurate, but probably not since the `src/agenttest` directory doesn't exist.

**Comment by bjkeller** [comment]
Done. We now have separate tests for the agents in different source sets.
