### ISSUE TITLE
Documentation for `--include-if-classname-appears`

### ISSUE THREAD

**Issue by mernst** [randoop/randoop#210]
The documentation of `--include-if-classname-appears` is confusing.  I don't think it belongs in the "Code under test: which methods may be called by a test" section of the command-line arguments, because it is about which methods *must* be called by a test.  It fits better in the "Which tests to output" section.

The terminology "include" is also confusing.  We should change it.  Here are some ideas:

 * `--require-classname-in-test`
 * `--output-if-classname-appears`

Its documentation should also clarify that it essentially marks tests that do not contain the given class name as invalid and does not output them.  So maybe it could appear in the "Test classification" section of command-line options, as

 * `--invalid-unless-classname-appears`

**Comment by bjkeller** [comment]
addressed in commit https://github.com/randoop/randoop/commit/9537537b56c9a3b0956959dfc577d107bbb7f146
