### ISSUE TITLE
"Exercised" versus "covered"

### ISSUE THREAD

**Issue by mernst** [randoop/randoop#211]
The documentation and code inconsistently use "exercised" and "covered".  It's often "exercised", as in `ExercisedClassVisitor`, `ExercisedClassTransformer`, and `exercisedClasses`.  However, there is also variable `coveredClassnames`, class `SpecialCoveredClassTest`, and file `instrument/testcase/coveredclasses.txt`.  Let's choose one term and make this consistent throughout the documentation and code.  Otherwise it is too difficult to keep track of which variables are related to which other ones.

**Comment by bjkeller** [comment]
switching "exercised" to "covered"

**Comment by mernst** [comment]
I found more uses of "exercise", and fixed them in commit 9987167.
