### ISSUE TITLE
Run `verifyGoogleJavaFormat` Gradle task earlier

### ISSUE THREAD

**Issue by mernst** [randoop/randoop#212]
The `verifyGoogleJavaFormat` Gradle task is cheap and fails frequently (at least for me), but it runs at the end of `./gradlew build`.  Can we make it run at or near the beginning instead?

**Comment by bjkeller** [comment]
It seems like it should come after compiling, but the plugin is making it a dependency for the check task.

The cleanest solution would probably be to create our own tasks and then (I think ) it should be possible to add the verify as a dependency to any compile task.

**Comment by bjkeller** [comment]
The task now runs before any task of type `JavaCompile`.

**Comment by bjkeller** [comment]
After working most of the day with this change, I altered the build to run `googleJavaFormat` before each compile. The reason is that nearly every build was failing, forcing me to run `googleJavaFormat` and then running the build again.
