### ISSUE TITLE
Enabling operation history logging

### ISSUE THREAD

**Issue by mernst** [randoop/randoop#215]
Is it necessary to use both --log-operation-history and --operation-history-log to enable logging?  This is by contrast to how --selection-log works.  I think the selection-log mechanism is less error-prone.  Please adapt Randoop to have just one command-line argument for the operation history.

It's confusing that the -Drandoop.operation.history.log=operation-log.txt mechanism only works for system tests, not other sorts of tests.  It would be nice if it worked more generally.
I'm not sure how to set logging for a specific unit test within the unit test's source code, given that the GenTests.handle routine sets logging but isn't called by unit tests, which create a ForwardGenerator directly and then call explore() on it without calling GenTests.handle.

**Comment by bjkeller** [comment]
For the operation history, if you give a file, it will just do the one.  I originally set this up to have the option of having logs written to standard out, but can modify it to use the plume.SimpleLog like the selection log.

**Comment by mernst** [comment]
Can you clarify "if you give a file"?  (I'm not sure which part of my issue you are responding to.  I'm trying to enable output for a specific unit test.)

**Comment by bjkeller** [comment]
If you are using --operation-history-log, you provide a file.

Define "unit test". A class in `src/test`?

**Comment by bjkeller** [comment]
System level logging is only going to make sense in certain test classes in `src/test`. 
Can you give me an example class that you would like to be able to run with logging?

**Comment by bjkeller** [comment]
The following has been pushed to master:
1. removed  `--log-operation-history`
2. both `--operation-history-log` and `--selection-history-log` can be given a hyphen `-` in addition to a file name
3. the build script will now pass `-Drandoop.` system properties to any test.

The third item only partially addresses your second issue, since the logging mechanism is managed in `randoop.main.GenTests`.

**Comment by mernst** [comment]
By "unit test" I meant classes in `src/test`.  Is there a better name for them?

Some of the tests I am investigating are:
```randoop.instrument.CoveredClassTest > testNameFilter STANDARD_OUT
randoop.instrument.SpecialCoveredClassTest > abstractClassTest STANDARD_OUT
randoop.test.ForwardExplorerTests > test2
randoop.test.ForwardExplorerTests > test4 STANDARD_OUT
randoop.generation.TestFilteringTest > matchOutputTest STANDARD_OUT
randoop.generation.TestFilteringTest > noRegressionOutputTest STANDARD_OUT
randoop.generation.TestFilteringTest > noOutputTest STANDARD_OUT
randoop.generation.TestFilteringTest > noErrorOrRegressionOutputTest STANDARD_OUT
randoop.generation.TestFilteringTest > noErrorOutputTest STANDARD_OUT
randoop.generation.TestFilteringTest > nonemptyOutputTest STANDARD_OUT
```

Thanks.

**Comment by bjkeller** [comment]
I'm pushing a change that allows turning on the generation-related logging using the system properties for the listed tests in `src/test`.  You can turn on selection logging for `randoop.instrument.SpecialCoveredClassTest`, but operation logging is not working yet. 

If you run into another test in `src/test` that needs the logging, let me know.  But, it is simple to set these up:
1. For selection logging, add a call to `TestUtils.setSelectionLog()` either in the `@BeforeClass` method if there is one, or at the beginning of the test method. 
2. For operation history logging, wrap the call to `generator.explore()`, where `generator` is the `ForwardGenerator` object, like this:
```
TestUtils.setOperation(generator);
generator.explore();
explorer.getOperationHistory().outputTable()
```

I have to fix a path problem for `src/coveredtest` that is affecting the operation history log (as mentioned above), so I'll keep this open.
