### ISSUE TITLE
Why does it create tests with "NoClassDefFoundError" when the class exists?

### ISSUE THREAD

**Issue by yeikel** [randoop/randoop#216]
I am trying to understand how randoop works , but sometimes It creates test cases that I do not understand why is that the case. 

For example: 

```
 @Test
    public void test03() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test03");
        CSVProcess cSVProcess0 = new CSVProcess();
        org.apache.poi.xssf.usermodel.XSSFSheet xSSFSheet1 = null;
        try {
            cSVProcess0.setHeader(xSSFSheet1);
            org.junit.Assert.fail("Expected exception of type java.lang.NoClassDefFoundError");
        } catch (java.lang.NoClassDefFoundError e) {
        }
    }
```
In this case , I am running randoop against **CSVProcess** , and inside that class I am using Apache poi as well. 

In my classpath, I included both the location of Apache POI and the class that I am trying to generate the tests. 

I do not get any error when creating the tests. 

https://image.prntscr.com/image/PxIRex-OTFSTklnbKL4J2w.png

What am I missing?

**Comment by mernst** [comment]
I'm sorry you are having trouble.  We would like to help you, but you have not provided enough information for us to reproduce, understand, and debug your problem and verify a fix.  Please provide the information requested in the [instructions for bug reporting in the Randoop manual](https://randoop.github.io/randoop/manual/#bug-reporting).  Thanks!

**Comment by bjkeller** [comment]
In terms of understanding Randoop, you should know that Randoop uses the classpath that it is run with. Classes can require complex configurations that need to be reflected on the classpath. In this case, if the classpath reflects a bad configuration, then Randoop will capture the behavior for that configuration.

In your case, the exception suggests that some class that `CSVProcess` uses is not on the classpath.  For more detailed help, see Mike's comment.

**Comment by yeikel** [comment]
@bjkeller I understand. I had this behavior with other classes before, but usually, I received a "class not found" message where I was able to add the corresponding dependencies to the classpath. 

In that specific class, I am using dependency injection through Spring, and I think that this is most likely the reason.  In similar classes within the same project, where dependency injection is not in place, I did have this problem. 

Do you have any idea if this is possible?

**Comment by bjkeller** [comment]
@yeikel The exception means that the class definition was on the classpath during compilation but is not on the classpath used for the Randoop run.  It seems unlikely to me that this exception is related to dependency injection, but without details I cannot really say.

**Comment by pmop** [comment]
Hello. I have been having the same issue trying to use Randoop.
More information in the picture attached.
![pramandar](https://user-images.githubusercontent.com/8449810/28985027-1011e10e-7937-11e7-8434-035bf71cc6e2.png)

**Comment by bjkeller** [comment]
Please post the java files instead of an image. Also paste your command into the comment box.

**Comment by pmop** [comment]
test7 project, with everything : [test7.zip](https://github.com/randoop/randoop/files/1202692/test7.zip)
Command used:
`java -ea -cp $(pwd):$(pwd)/*:./programs/ randoop.main.Main gentests --timelimit=10 --testclass test7.in.Package_0.ClassId_0`

(Here, on my machine, test7 folder is within ./programs, as shown in the picture)

**Comment by mernst** [comment]
I tried to run the following commands:
```
cd ~/tmp
wget https://github.com/randoop/randoop/files/1202692/test7.zip
unzip test7
cd test7
java -ea -cp $(pwd):$(pwd)/*:./programs/ randoop.main.Main gentests --timelimit=10 --testclass test7.in.Package_0.ClassId_0
```
The result was:
```
Error: Could not find or load main class randoop.main.Main
```

This is much better, but could you please provide a complete test case with exact instructions, starting from no assumptions about what is installed or other files on your file system?
Thanks!  I'd like to help you as soon as there is a test case that I can reproduce.

**Comment by pmop** [comment]
@mernst Probably a problem with classpath
To make it clear, I no longer face any issues with Randoop.
The solution was fixing a typo:
`java -ea -cp $CLASSPATHSTUFF randoop.main.Main gentests --timelimit=10 --testclass test7.in.Package_0.ClassId_0`
Should be:
`java -ea -cp $CLASSPATHSTUFF randoop.main.Main gentests --timelimit=10 --testclass=test7.in.Package_0.ClassId_0`
Notice '=' on "--testclass" was missing.

Thank you for your time!

**Comment by mernst** [comment]
Ah, that is a simple issue, but enough to prevent the JVM from running.
Thanks for the followup, and I'm glad that everything is working for you now!
I'm going to close the issue, but let us know if you have other problems.

**Comment by tranglq** [comment]
Hi! I have a similar problem. My project uses RealMatrix.java in apache-common-math3 library. I tried to generate unit test but ...
![image](https://user-images.githubusercontent.com/31271267/46260286-1a85f200-c50e-11e8-86ca-029e3f09daf9.png)

My command line:` java -classpath ..\Randoop\randoop-all-4.0.4.jar;..\Project\commons-math3-3.6.1\commons-math3-3.6.1-sources.jar;..\Project\MatrixProject\out\production\MatrixProject\ -Xmx3000m randoop.main.Main gentests --testclass=NhanMaTran --output-limit=5`

Error: `java.lang.NoClassDefFoundError: org/apache/commons/math3/linear/RealMatrix`

What can I do?

**Comment by mernst** [comment]
Your classpath does not contain `commons-math3-3.6.1.jar` as it needs to.
Your classpath contains file `commons-math3-3.6.1-sources.jar`, which contains `.java` files but not `.class` files.
