### ISSUE TITLE
How can I read a .classpath file from Eclipse?

### ISSUE THREAD

**Issue by yeikel** [randoop/randoop#217]
Rather than a bug, this is a feature request. 

When using Eclipse, and setting different dependencies, Eclipse generates the class path dependencies in a file called ".classpath" that looks like (for Maven in this case) : 

	<classpathentry kind="var" path="M2_REPO/org/codehaus/jackson/jackson-mapper-asl/1.9.8/jackson-mapper-asl-1.9.8.jar"/>

Now, I think it would be very useful. If randoop was able to read this file and build the classpath based on it, rather than me having to declare the dependencies when calling it, especially when the project gets large and I need to manage multiple dependencies.

My current sample run: 

> java -ea -classpath C:\dev\dev\target\classes\;C:\Users\Yeikel\.m2\repository\org\aspectj\aspectjrt\1.8.10\aspectjrt-1.8.10.jar;r;C:/Randoop/randoop-all-3.1.5.jar randoop.main.Main gentests --classlist=classes.txt --timelimit=20

Desired sample run: 

> java -ea -classpath C:\dev\dev\.classpath;C:\dev\dev\target\classes\;C:/Randoop/randoop-all-3.1.5.jar randoop.main.Main gentests --classlist=classes.txt --timelimit=20

**Comment by mernst** [comment]
It sounds like this could shorten the command line.
However, the `-classpath` command-line argument is an argument to `java`, not to Randoop.
Therefore, please submit this suggestion to Oracle.
