### ISSUE TITLE
com.github.javaparser

### ISSUE THREAD

**Issue by ms140400344** [randoop/randoop#223]
Which version of "javaparser or javalang" needed for the Class CompilationUnit.java in randoop.output folder

**Comment by mernst** [comment]
Randoop uses the correct one automatically.

Your comment does not make sense, and it is not an issue.  Please follow the instructions in the Randoop manual when submitting issues.

**Comment by ms140400344** [comment]
Thank for repling

**Comment by ms140400344** [comment]
Thank for repling
