### ISSUE TITLE
Resolve whether concurrent map is necessary in CallReplacementTransformer

### ISSUE THREAD

**Issue by bjkeller** [randoop/randoop#230]
I introduced the use of the `ConcurrentHashMap` in the replace call agent due to some issue, but now there is a question whether it is necessary. 

Experiments need to be done with threads enabled to determine if there is an issue using a non-concurrent map. If not, the `ConcurrentHashMap` can be replaced by a `HashMap`. If so, the reasons for the concurrent map should be documented.

**Comment by markro49** [comment]
I believe a ConcurrentHasMap is not necessary. 
 I have replaced it with a standard HashMap in this commit: https://github.com/randoop/randoop/commit/375f98de64365ee63721949141096fbcb8eaefbe
