### ISSUE TITLE
Running sequences during generation in a clean directory

### ISSUE THREAD

**Issue by bjkeller** [randoop/randoop#233]
Having sequences run in a clean directory could resolve the generation of file-related flaky tests.

However, sequences are run with reflection, the working directory is that of Randoop and it doesn't seem to be possible to set the working directory on the fly.  Possible solutions involve using a separate process, because it is possible to set the working directory for a new process, and then either
- run generation in the process, with the working directory cleaned of files between each sequence execution, or
- run each sequence in a separate process (which may not be easy to do) with a new working directory.

**Comment by mernst** [comment]
This sounds valuable.  However, there is no test case illustrating the problem, so it would be difficult to verify a fix.  I'm closing this for now; we can reopen it if someone has a reproducible problem.
