### ISSUE TITLE
Miss file:  randoop.MethodReplacements;

### ISSUE THREAD

**Issue by wupflove** [randoop/randoop#299]
Thanks for submitting an issue.  Please see the [instructions for submitting an issue](https://randoop.github.io/randoop/manual/#bug-reporting) to ensure that your report is not missing important information.

randoop/src/main/java/randoop/main/GenTests.java 
39: import randoop.MethodReplacements;

but the java file MethodReplacements do not exist，please check it!

thanks

**Comment by mernst** [comment]
The file does exist.  See https://github.com/randoop/randoop/blob/master/agent/replacecall/src/main/java/randoop/MethodReplacements.java .
