### ISSUE TITLE
Spring annotations gives nullpointerexception while generating tests

### ISSUE THREAD

**Issue by mydata** [randoop/randoop#302]
We are trying to generate the JUnit test cases using randoop for Spring based application. We get Nullpointer exception for objects, which has been injected using @Inject annotaion, while generating tests. is there any way this can get to successful test generation?

**Comment by mernst** [comment]
It's hard to know from the information you have provided.  Could you follow the [instructions for reporting bugs](https://randoop.github.io/randoop/manual/index.html#getting_help), including a complete, reproducible, minimal test case?  That will enable us to help you.

**Comment by mernst** [comment]
I'm closing this issue because the original submitter did not provide a reproducible test case.
