### ISSUE TITLE
Suppress if (debug) block

### ISSUE THREAD

**Issue by rdifrango** [randoop/randoop#303]
I read and re-read the manual but wanted to see if there is an option to suppress the creation of the following block:

```
if (debug)
    System.out.format("%n%s%n", "RegressionTest3.test006");
```

**Comment by mernst** [comment]
The if statement is created by [this line](https://github.com/randoop/randoop/blob/master/src/main/java/randoop/output/JUnitCreator.java#L290).  You could comment it out and re-compile Randoop.

What motivates your desire to remove the statement?

**Comment by mernst** [comment]
I'm closing this because there was no response from the original submitter.
