### ISSUE TITLE
Unable to load the specification operation 

### ISSUE THREAD

**Issue by ryp123** [randoop/randoop#311]
Randoop Version: 4.0.0 

I have the following code snippet which produces the error

```java

public enum Fake {
 One, Two;

  public Fake fromString(String posEnum) throws RuntimeException {
    switch(posEnum) {
      case "one": return Fake.One;
      case "two": return  Fake.Two;
      default: throw new RuntimeException("invalid input!");
    }
  }
}
```

And the following specs.json file 

```json
[
  {
    "operation": {
      "classname": "Fake",
      "name": "toString",
      "parameterTypes": ["String"]
    },
    "identifiers": {
     "parameters": [
       "posEnum"
     ]
   }
  }
]
```

I receive the following output 

```
Error in conditions: Could not load specification operation: {
 "classname": "Fake",
 "name": "toString",
 "parameterTypes": "[String]"
} while reading file specs.json: String

```

Furthermore, the command that I am using is 

```bash
java -ea -cp build/classes/java/main/:randoop-all-4.0.0.jar randoop.main.Main gentests --testclass=Fake --junit-output-dir=src/test/java/ --time-limit=20 --specifications=specs.json
```

I am just learning the framework so my apologies if I am just formatting something incorrectly.

**Comment by ryp123** [comment]
Never mind, I see the issue.

**Comment by mernst** [comment]
I'm glad you figured it out!  Feel free to ask about future problems.
Can you suggest ways to improve Randoop's diagnostic messages, so others will not be confused in the future?

**Comment by ryp123** [comment]
@mernst I am not sure if it possible, but in this case it was because for whatever sleep derived reason I put toString instead of fromString. Accordingly, indicating that the class doesn't have this particular method would make the error message much more readable. As for the parameterType I don't think the error is necessarily bad, but I do think the docs should specify that you need to give the full class path for objects, but not for primitives.
