### ISSUE TITLE
Randoop Failed in an Unexpected Way randoop.BugInRandoopException

### ISSUE THREAD

**Issue by WilliamCao13** [randoop/randoop#341]
Version of Randoop: 4.0.3

Commands to Reproduce:

```
git clone https://github.com/WilliamCao13/json-schema-core.git
cd json-schema-core
./gradlew build
# (may need to run more than once (w/o cleaning) as the build fails periodically)
./gradlew build
./gradlew test --rerun-tasks
./gradlew jacocoTestReport
# (place randoop-all-4.0.3.jar in the json-schema-core directory)
# (place classStripped.txt in the json-schema-core directory)
java -ea -classpath "./build/classes/main/:/usr/share/java/junit4.jar:/usr/share/java/hamcrest-core.jar:./randoop-all-4.0.3.jar" randoop.main.Main gentests --classlist=classStripped.txt --time-limit=60
```

Here is the classStripped.txt that was used in the command:
[classStripped.txt](https://github.com/randoop/randoop/files/1909831/classStripped.txt)

The output for the commands:
[build.txt](https://github.com/randoop/randoop/files/1909911/build.txt)
[test.txt](https://github.com/randoop/randoop/files/1909912/test.txt)
[report.txt](https://github.com/randoop/randoop/files/1909913/report.txt)
[randoopError.txt](https://github.com/randoop/randoop/files/1909915/randoopError.txt)

**Comment by mernst** [comment]
Thanks for the specific and concrete bug report; I appreciate it.
I got exactly as many test inputs generated as you did (102), but I was unable to reproduce the problem:  Randoop successfully produced output.

I tried unsuccessfuly to reproduce the problem on both CentOS:
```Linux godwit.cs.washington.edu 4.9.84-1.el7.retpoline.x86_64 #1 SMP Sun Feb 25 15:56:57 PST 2018 x86_64 x86_64 x86_64 GNU/Linux```
and on Ubuntu:
```Linux mdet430s 4.13.0-38-generic #43-Ubuntu SMP Wed Mar 14 15:20:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux```

I'm going to mark this as unreprodcible for now, but I would welcome information to permit me to reproduce it.  For example, what operating system were you using?m

**Comment by WilliamCao13** [comment]
Running "lsb_release -a" in the terminal shows the following:

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

Let me try with a different operating system and see if I can reproduce the results.

Thanks for the quick follow up.

**Comment by mernst** [comment]
FYI, the Ubuntu I tried it on is
```
% lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
```

**Comment by mernst** [comment]
Interesting.  So, there is some problem here, but I'm not sure how the OS is affecting it.
The next step is for one of the Randoop developers to create an Ubuntu 16.04 virtual machine and try your test case within it.
Thanks for the followup!  I appreciate it.

**Comment by mernst** [comment]
I tried the following commands on WSL running Ubuntu 18.04.
Here are the exact commands I ran (no manual steps are required):

```
git clone https://github.com/WilliamCao13/json-schema-core.git
cd json-schema-core
./gradlew build || ./gradlew build
./gradlew test --rerun-tasks
./gradlew jacocoTestReport
wget https://github.com/randoop/randoop/releases/download/v4.0.3/randoop-all-4.0.3.jar
wget https://github.com/randoop/randoop/files/1909831/classStripped.txt
java -ea -classpath "./build/classes/main/:/usr/share/java/junit4.jar:/usr/share/java/hamcrest-core.jar:./randoop-all-4.0.3.jar" randoop.main.Main gentests --classlist=classStripped.txt --time-limit=60
```

I could not reproduce the problem.

Then, I installed an Ubuntu 16.04 from the Microsoft Store.
I ran these commands:

```
sudo apt-get update
sudo apt-get install -y openjdk-8-jdk
```

and then ran the exact commands above.
Again, I could not reproduce the problem.

Is the problem deterministic and reproducible for you?
Could it have to do with your environment?

Could you please try reproducing your problem again, using the above instructions and a fresh Ubuntu 16.04 (not an existing Ubuntu 16.04)?

Even better, could you try with the latest version of Randoop from its version control repository?  I have recently added some debugging output that may help to indicate the problem.  (You'll need to build Randoop; let me know if you cannot, and I'll send you a jar.)

**Comment by WilliamCao13** [comment]
Note: These results are from a new machine with a fresh Windows 10 installation (1803 update build 17134). 

After installing Ubuntu 16.04 from the Microsoft Store and running the supplied commands using Randoop 4.0.3, I was unable to reproduce the bug.

When I used ```randoop-all-4.0.4.jar``` from the releases, I was still unable to reproduce the results.

Unfortunately, after cloning the Randoop repository and attempting to build running ```./gradlew jar```, it failed with an exception.

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred evaluating root project 'randoop'.
> A problem occurred starting process 'command 'html5validator''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

Here is the output from stderr and stdout when running the following command: 
 ```./gradlew --stacktrace --debug jar >> buildLog.txt 2>&1```
[buildLog.txt](https://github.com/randoop/randoop/files/2096239/buildLog.txt)

**Comment by mernst** [comment]
OK, I think this verifies that your environment was broken in some way when you first reported the problem.  (I'm not sure whether you ever verified that the problem was verifiable -- did you?)

The problem with html5validator is because you didn't follow the instructions at https://randoop.github.io/randoop/manual/dev.html#prerequisites

**Comment by mernst** [comment]
The error message was confusing, when the prerequisites are not installed.
I improved it in commit 6bff86f.  I hope that helps!

**Comment by mernst** [comment]
Thanks for doing that.  We have tried hard to reproduce the error, on multiple OSes.  I (hopefully) expect that the failure was transient.  But if we can reproduce it, we will fix it!

**Comment by WilliamCao13** [comment]
After doing a clean install of Ubuntu 16.04 on the original machine and running the commands, I was unable to reproduce the error. The failure was probably transient.

**Comment by mernst** [comment]
Thanks for verifying; I appreciate it.  If you have other problems, please let us know.
