### ISSUE TITLE
randoop  --methodlist encounter errors

### ISSUE THREAD

**Issue by zjzh** [randoop/randoop#343]
When I want to generate HashSet testsuites ,I write the command:
java randoop.main.Main --class=java.util.HashSet --methodlist=mymethods.txt --timelimit=10
But it fails!
information is:
Error: parse exception thrown randoop.operation.OperationParseException: A statement description must be of the form <id> : <description> but the statement "java.util.HahSet(java.util.Collection)" does not have a valid form (no colon).

Someone know why??Thank you

![image](https://user-images.githubusercontent.com/29055749/38765969-a7219a20-3ffd-11e8-8984-c306076fbbbe.png)
![image](https://user-images.githubusercontent.com/29055749/38765998-fb8d9f8c-3ffd-11e8-91a9-927519a296bf.png)

**Comment by zjzh** [comment]
Sorry the parse exception,when I modified it ,I encounterd another error :Anyone knows reasons?
![image](https://user-images.githubusercontent.com/29055749/38778130-ce1aa358-40e6-11e8-8e3e-273ddcfb2c59.png)
Throwable thrown while handling command: java.lang.StringIndexOutOfBoundsExcepti
on: String index out of range: -1
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(Unknown [Source)]
        at randoop.operation.ConstructorCall.parse(ConstructorCall.java:246)
        at randoop.operation.OperationParser.parse(OperationParser.java:79)
        at randoop.reflection.OperationModel.addOperations(OperationModel.java:4
10)
        at randoop.reflection.OperationModel.createModel(OperationModel.java:142
)
        at randoop.main.GenTests.handle(GenTests.java:245)
        at randoop.main.Main.nonStaticMain(Main.java:62)
        at randoop.main.Main.main(Main.java:26)

Randoop failed.
Last sequence under execution:
null

**Comment by mernst** [comment]
I'm sorry you are having trouble.
My first suggestion is to use the current version of Randoop (4.0.3) rather than an old version (3.1.5).
If the problem persists, could you please provide your current `mymethods.txt` file (as text, not a screenshot)?  Then we can reproduce and fix the problem for you.

**Comment by zjzh** [comment]
Thanks for your suggestions,I use the new version(4.0.3),it's successful!
I used to be confused that example file of Randoop Manual seems not correct.(https://randoop.github.io/randoop/manual/#option:methodlist )Now,it's my mistake.

**Comment by mernst** [comment]
I am glad this is working for you now.
