### ISSUE TITLE
Change initial contents of int pool

### ISSUE THREAD

**Issue by ankp67** [randoop/randoop#354]
I do not want use the literal value -1 in integer, so going through randoop manual I found that we can use --literals-level=NONE to not use the values specified via the literal file. But when I run the randoop with the command as:

java -classpath C:\randoop-3.1.5\bin;C:\randoop-3.1.5\randoop-all-3.1.5.jar randoop.main.Main gentests --testclass=triangle_validity --testsperfile=4000 --literals-level=NONE --literals-file=literalsfile

I get the following exception:

Throwable thrown while handling command: java.lang.RuntimeException: Invalid parameter combination: specified a class literal file but --use-class-literals=NONE
java.lang.RuntimeException: Invalid parameter combination: specified a class literal file but --use-class-literals=NONE
        at randoop.main.GenInputsAbstract.checkOptionsValid(GenInputsAbstract.java:634)
        at randoop.main.GenTests.handle(GenTests.java:144)
        at randoop.main.Main.nonStaticMain(Main.java:62)
        at randoop.main.Main.main(Main.java:26)

Could you please help!!!

I am attaching the literal file.
[literalsfile.txt](https://github.com/randoop/randoop/files/1968304/literalsfile.txt)

**Comment by mernst** [comment]
The [documentation for `--literals-level-NONE`](https://randoop.github.io/randoop/manual/index.html#option:literals-level) says:

> Do not use literals specified in a literals file.

So, it does not make sense to supply both `--literals-level=NONE` and `--literals-file`.

What is the result if you don't supply `--literals-level`, but only `--literals-file`?

**Comment by mernst** [comment]
I see.  This is much clearer.
Currently, there is not a way to change those constants.

You can edit Randoop's source code to add a new command-line option to control the hard-coded initial constants, and make a pull request.

However, you probably want to prevent all negative values, not just -1, and you probably want to prevent them as input only to specific methods, not all methods.  Supplying a [specification](https://randoop.github.io/randoop/manual/index.html#spec-json-method-specifications) for the relevant methods is a way to do this.

**Comment by ankp67** [comment]
Okk thanks
