### ISSUE TITLE
Problem when I try to call randoop twice: java.nio.file.FileSystemAlreadyExistsException.

### ISSUE THREAD

**Issue by leofernandesmo** [randoop/randoop#355]
I'm using Randoop (4.0.3) as lib in my application.
So, I invoke Randoop to generate the test suite:

```
Main m = new Main();
String[] argsRandoop = { "gentests", "--methodlist="...", ...};
m.nonStaticMain(argsRandoop);

```
For the first execution, it works fine, but if I try to call Randoop twice or more it raises:

> Throwable thrown while handling command: java.nio.file.FileSystemAlreadyExistsException
> java.nio.file.FileSystemAlreadyExistsException
> at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:113)
> at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
> at java.nio.file.FileSystems.newFileSystem(FileSystems.java:276)
> at randoop.main.GenTests.getResourceDirectoryPath(GenTests.java:1000)
> at randoop.main.GenTests.getJDKSpecificationFiles(GenTests.java:969)
> at randoop.main.GenTests.handle(GenTests.java:262)
> at randoop.main.Main.nonStaticMain(Main.java:65)
> at ...
> 

It is because in the method `GenTest.getResourceDirectoryPath(String)` randoop creates a new `FileSystem (FileSystems.newFileSystem(directoryURI, Collections.<String, Object>emptyMap()))`.
Maybe, it should check if a FileSystem already exists, or implement some method to "reset caches".

Is this the expected behavior? Or can we consider this as a bug?

**Comment by mernst** [comment]
Thanks for reporting this problem.  I consider it a bug.
If you have a proposed fix, feel free to submit a pull request.
Otherwise, we'll get to this as soon as we have a chance.

**Comment by VincentBUBU** [comment]
We met the same issue.

This is a proposed solution (use of a try-with-resources statement for 'FileSystems.newFileSystem'):

```java
private Path getResourceDirectoryPath(String resourceDirectory) {
	URI directoryURI;
	try {
		directoryURI = GenTests.class.getResource(resourceDirectory).toURI();
	} catch (URISyntaxException e) {
		throw new RandoopBug("Error locating directory " + resourceDirectory, e);
	}

	Path path = null;
	try (FileSystem fileSystem = FileSystems.newFileSystem(directoryURI, Collections.<String, Object>emptyMap())) {
		path = fileSystem.getPath(resourceDirectory);
	} catch (IOException e) {
		throw new RandoopBug("Error locating directory " + resourceDirectory, e);
	}
	return path;
}
```

_(thanks to CLE and ALE for their analysis)_

**Comment by mernst** [comment]
Thanks for the proposal.  Your proposed change does not fix the problem.  It changes a `FileSystemAlreadyExistsException` into a `RandoopBug`, but in either case Randoop crashes.

I have opened a pull request that fixes the issue in the way the original poster suggested.

**Comment by mernst** [comment]
Thanks for re-raising this issue.  I appreciate it.

I suspect that your solution would work, but the JDK documentation does not guarantee it, so I went with a cache.
