### ISSUE TITLE
NullPointerException when specified progressdisplay argument to False 

### ISSUE THREAD

**Issue by leofernandesmo** [randoop/randoop#356]
Randoop Version: 4.0.3
Command:
`java -Xmx3000m -cp .:randoop-all-4.0.3.jar randoop.main.Main gentests --testclass=java.util.Date --time-limit=10 --progressdisplay=false`

Output:

> 
> Throwable thrown while handling command: java.lang.NullPointerException
> java.lang.NullPointerException
> 	at randoop.generation.AbstractGenerator.createAndClassifySequences(AbstractGenerator.java:312)
> 	at randoop.main.GenTests.handle(GenTests.java:454)
> 	at randoop.main.Main.nonStaticMain(Main.java:65)
> 	at randoop.main.Main.main(Main.java:29)

> Randoop failed.
> Last sequence under execution: 
> java.util.Date date1 = new java.util.Date((long)118);
> int int2 = date1.getDate();
> int int3 = date1.getDate();
> int int4 = date1.getYear();
>

**Comment by mernst** [comment]
Thanks for reporting the problem!

By the way, generating tests for a nondeterministic class such as Date (the same code returns different values on different runs) is likely to lead to [flaky tests](https://randoop.github.io/randoop/manual/index.html#nondeterminism).
