### ISSUE TITLE
Randoop seems to ignore given specification

### ISSUE THREAD

**Issue by ariannab** [randoop/randoop#375]
I am using the latest version of Randoop cloned from master branch.
Randoop produces an error-revealing test case even tough a specification is telling it that such error is expected. When executing the test case, this is the output:
```
 java.lang.NullPointerException
        at org.apache.commons.collections4.iterators.EnumerationIterator.hasNext(EnumerationIterator.java:82)
        at ErrorTest0.test1(ErrorTest0.java:18)
```

Such test case (for which I attach the source code) instantiates a `org.apache.commons.collections4.iterators.EnumerationIterator` object and then invokes method `hasNext()`. See line 45 and 81 of the class source code: https://github.com/apache/commons-collections/blob/collections-4.1/src/main/java/org/apache/commons/collections4/iterators/EnumerationIterator.java.

This is the specification related to the method:
```
{
    "operation": {
      "classname": "org.apache.commons.collections4.iterators.EnumerationIterator",
      "name": "hasNext",
      "parameterTypes": []
    },
    "identifiers": {
      "parameters": [],
      "receiverName": "receiverObjectID",
      "returnName": "methodResultID"
    },
    "throws": [
      {
        "exception": "java.lang.NullPointerException",
        "description": "@throws java.lang.NullPointerException the underlying enumeration is null.",
        "guard": {
          "condition": "receiverObjectID.getEnumeration()==null",
          "description": "the underlying enumeration is null."
        }
      }
    ],
    "post": [],
    "pre": []
  },
```

The `enumeration` field that the specification is talking about is indeed set to `null` in the constructor used by Randoop, and thus the exception is expected. 
I already used Randoop with specifications and normally the integration works. 

Test case source code:
[ErrorTest0.txt](https://github.com/randoop/randoop/files/2075583/ErrorTest0.txt)

Randoop command:
```
java -ea -cp commons-collections4-4.1.jar:randoop.jar randoop.main.Main gentests 
--classlist=evallist.txt, 
--time-limit=900, 
--stop-on-error-test, 
--junit-output-dir=./src/test/java 
--flaky-test-behavior=DISCARD 
--no-regression-tests 
--log=randoop-log.tx
--omitmethods= org\.apache\.commons\.collections4\.MultiMapUtils\.getCollection
```

Specifications:
[specifications.zip](https://github.com/randoop/randoop/files/2075600/specifications.zip)

Commons collections jar:
http://central.maven.org/maven2/org/apache/commons/commons-collections4/4.1/commons-collections4-4.1.jar

**Comment by ariannab** [comment]
I think the problem relates to the receiver name - `receiverObjectID`. While running Randoop on another class of another project, I got the following error:
```
Error: Condition method did not compile: cannot find symbol
  symbol:   variable receiverObjectID
  location: class org.graphstream.ui.graphicGraph.RandoopExpressionClass24
Class Declaration:
package org.graphstream.ui.graphicGraph;

public class RandoopExpressionClass24 {
  public static boolean MethodNameIsIrrelevant(java.lang.String id, org.graphstream.ui.graphicGraph.GraphicNode from, org.graphstream.ui.graphicGraph.GraphicNode to, boolean dir, java.util.HashMap attributes) throws Throwable {
    return receiverObjectID.isDirected();
  }
}
: Compilation failed
```

I am opening a new issue for this error.

**Comment by mernst** [comment]
Can you provide the `evallist.txt` file used in your command, to enable me to reproduce the problem?

**Comment by ariannab** [comment]
Should be this one:
[commons-coll-evallist.txt](https://github.com/randoop/randoop/files/2087070/commons-coll-evallist.txt)

**Comment by mernst** [comment]
This bug arises only for methods in generic classes.  The bug is that the specification was attached to the original version, but not the instantiated version.
