### ISSUE TITLE
Problem with receiverName identifier in specifications

### ISSUE THREAD

**Issue by ariannab** [randoop/randoop#376]
I am using the latest version of Randoop cloned from master branch.
Randoop is giving me the following compilation error while running with specifications:
```
Error: Condition method did not compile: cannot find symbol
  symbol:   variable receiverObjectID
  location: class org.graphstream.ui.graphicGraph.RandoopExpressionClass24
Class Declaration:
package org.graphstream.ui.graphicGraph;

public class RandoopExpressionClass24 {
  public static boolean MethodNameIsIrrelevant(java.lang.String id, org.graphstream.ui.graphicGraph.GraphicNode from, org.graphstream.ui.graphicGraph.GraphicNode to, boolean dir, java.util.HashMap attributes) throws Throwable {
    return receiverObjectID.isDirected();
  }
}
: Compilation failed
```
In the specifications, `receiverObjectID` is the value of the `receiverName` identifier:
```
[
  {
    "operation": {
      "classname": "org.graphstream.ui.graphicGraph.GraphicEdge",
      "name": "org.graphstream.ui.graphicGraph.GraphicEdge",
      "parameterTypes": [
        "java.lang.String",
        "org.graphstream.ui.graphicGraph.GraphicNode",
        "org.graphstream.ui.graphicGraph.GraphicNode",
        "boolean",
        "java.util.HashMap"
      ]
    },
    "identifiers": {
      "parameters": [
        "id",
        "from",
        "to",
        "dir",
        "attributes"
      ],
      "receiverName": "receiverObjectID",
      "returnName": "methodResultID"
    },
    "throws": [],
    "post": [],
    "pre": [
      {
        "description": "@param dir dir is True. True if the edge is directed in the direction from-to.",
        "guard": {
          "condition": "receiverObjectID.isDirected()",
          "description": "dir is True. True if the edge is directed in the direction from-to."
        }
      }
    ]
  }
]
```

I am not sure whether I need to change something in the Toradocu-Randoop integration or if the problem lays in Randoop.

This is the base Randoop command:
```
java -ea -cp gs-core-1.3.jar:randoop.jar randoop.main.Main gentests 
--classlist=evallist.txt, 
--time-limit=900, 
--stop-on-error-test, 
--junit-output-dir=./src/test/java 
--flaky-test-behavior=DISCARD 
--no-regression-tests 
--log=randoop-log.tx
```

The specifications needed:
[specifications.zip](https://github.com/randoop/randoop/files/2080795/specifications.zip)

And here is Gs-core jar:
http://central.maven.org/maven2/org/graphstream/gs-core/1.3/gs-core-1.3.jar

**Comment by mernst** [comment]
Can you provide the file `evallist.txt` that is used in the command?
I need this to reproduce the error.
Thanks.

**Comment by ariannab** [comment]
Right, sorry. Should be this one:
[graphstream-evallist.txt](https://github.com/randoop/randoop/files/2087068/graphstream-evallist.txt)

**Comment by mernst** [comment]
Note: The given command does not work for me.  It is missing the `--specifications=specifications.zip` command-line argument, and the `specifications.zip` file is malformed (it contains a text file).

For reference, here are the commands that I used:

```
rm -rf randoop-log.txt org src specifications.zip gs-core-1.3.jar graphstream-evallist.txt

wget https://github.com/randoop/randoop/files/2080795/specifications.zip
wget https://repo1.maven.org/maven2/org/graphstream/gs-core/1.3/gs-core-1.3.jar
wget https://github.com/randoop/randoop/files/2087068/graphstream-evallist.txt
zip -d specifications.zip specifications/classlist.txt

java -ea -cp gs-core-1.3.jar:$randoop/build/libs/randoop-all-4.2.5.jar randoop.main.Main gentests \
  --classlist=graphstream-evallist.txt \
  --specifications=specifications.zip \
  --time-limit=900 \
  --stop-on-error-test \
  --junit-output-dir=./src/test/java \
  --flaky-test-behavior=DISCARD \
  --no-regression-tests \
  --log=randoop-log.txt \
  --omitmethods=org\.apache\.commons\.collections4\.MultiMapUtils\.getCollection
```

**Comment by mernst** [comment]
The problem is that the given specification is malformed.

The precondition mentions `receiverObjectID`:

```
          "condition": "receiverObjectID.isDirected()",
```

However, a constructor for a non-inner class has no receiver.

I think you need to change Toradocu so that it does not output invalid specifications whose condition uses non-existent variables.

The [original comment](https://data.graphstream-project.org/api/gs-core/1.3/org/graphstream/ui/graphicGraph/GraphicEdge.html) says:

```java
@param dir True if the edge is directed in the direction from-to.
```

and it seems to me that there is nothing for Toradocu to output in this case.
