### ISSUE TITLE
Error reading replacement file : Class not found ; even though the class is in the classpath

### ISSUE THREAD

**Issue by Godmode-bishal** [randoop/randoop#401]
**The error I get -**

Error reading replacement file C:\Human\workspace\Randoop\src\exchange\app\v0\model\replacecall-exclusions.txt:
  C:\Human\workspace\Randoop\src\exchange\app\v0\model\replacecall-exclusions.txt:1: Class not found: exchange/app/v0/model/randoop/OrderModelMock for line: exchange.app.v0.model.randoop.OrderModel.toString() exchange.app.v0.model.randoop.OrderModelMock.toString()

**This is my original code -**
`package exchange.app.v0.model.randoop;

import exchange.app.v0.model.OrderStatus;

import java.util.Calendar;
import java.util.Date;
import java.util.Objects;
import java.util.UUID;

public class OrderModel {
    private long id;
    private long quantity;
    private Date createdOn;
    private OrderStatus status;
    private String customerId;
    private UUID messageId;

    public OrderModel() {
        this.createdOn = Calendar.getInstance().getTime();
        this.status = OrderStatus.NEW;
    }

    public OrderModel(long id) {
        this();
        this.id = id;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getQuantity() {
        return quantity;
    }

    public void setQuantity(long quantity) {
        this.quantity = quantity;
    }

    public Date getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    public OrderStatus getStatus() {
        return status;
    }

    public void setStatus(OrderStatus status) {
        this.status = status;
    }

    public String getCustomerId() {
        return customerId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    public UUID getMessageId() {
        return messageId;
    }

    public void setMessageId(UUID messageId) {
        this.messageId = messageId;
    }

    @Override
    public String toString() {
        return "OrderModel {" +
                "messageId = " + messageId +
                ", orderId = " + id +
                ", quantity = " + quantity +
                ", createdOn = " + createdOn +
                ", status = " + status +
                ", customerId = " + customerId +
                '}';
    }

    @Override
    public boolean equals(Object obj) {
        if(this == obj) return true;
        if(!(obj instanceof OrderModel)) return false;
        OrderModel that = (OrderModel) obj;
        return id == that.id &&
                quantity == that.quantity &&
                Objects.equals(createdOn, that.createdOn) &&
                status == that.status &&
                Objects.equals(customerId, that.customerId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, quantity, createdOn, status, customerId);
    }
}
`

**This is my replacement mock -**

` package exchange.app.v0.model.randoop;

public class OrderModelMock {
    public String toString(OrderModel orderModel) {
        return "OrderModel {" +
                ", orderId = " + orderModel.getId() +
                ", quantity = " + orderModel.getQuantity() +
                ", status = " + orderModel.getStatus() +
                ", customerId = " + orderModel.getCustomerId() +
                '}';
    }
} `

**This is the content of replacement exclusions txt file -**

`exchange.app.v0.model.randoop.OrderModel.toString() exchange.app.v0.model.randoop.OrderModelMock.toString()
`

**Main class**  randoop.main.Main

**VM options** 
-Xbootclasspath/a:C:\Human\Downloads\randoop-4.0.4\replacecall-4.0.4.jar -javaagent:C:\Human\Downloads\randoop-4.0.4\replacecall-4.0.4.jar=--replacement-file=C:\Human\workspace\Randoop\src\exchange\app\v0\model\replacecall-exclusions.txt

**Program Arguments**
gentests --testclass=exchange.app.v0.model.randoop.OrderModel --ignore-condition-exception=true

The exception is thrown in

`Class<?> methodClass = Class.forName(this.classname);`
in MethodSignature.class

The class file of OrderModelMock is present in C:\Human\workspace\Randoop\out\production\Randoop

and I tried `System.getProperty("java.class.path")` and one of the locations is C:\Human\workspace\Randoop\out\production\Randoop.

I made a separate java program separately and checked `Class<?> methodClass = Class.forName("exchange.app.v0.model.randoop.OrderModelMock");`. No problem here. Class is found.

I am not sure if it's a bug or if I doing something wrong.

**Comment by Godmode-bishal** [comment]
Turns out it was an issue of the classloader. 
`Class<?>` methodClass = Class.forName(this.classname);`
in MethodSignature.class was using the Bootstrap classloader. 

Since OrderModelMock class was part of the classpath, it can be found only by the Application ClassLoader, not the Bootstrap ClassLoader. I had to separately add C:\Human\workspace\Randoop\out\production\Randoop to -Xbootclasspath. After that, the classloader was successfully able to find the class. **Unfortunately, these instructions aren't provided in the documentation.  Or maybe I missed something.**

Still, while writing the JUnit file, the program spits out another ClassNotFound Exception:

Class not found: exchange/app/v0/model/randoop/OrderModelMock for line: exchange.app.v0.model.randoop.OrderModel.toString() exchange.app.v0.model.randoop.OrderModelMock.toString()

`Standard output:

... end of standard output.

	at randoop.output.FailingTestFilter.numJunitFailures(FailingTestFilter.java:374)
	at randoop.output.FailingTestFilter.commentFailingAssertions(FailingTestFilter.java:245)
	at randoop.output.FailingTestFilter.writeClassCode(FailingTestFilter.java:120)
	at randoop.main.GenTests.writeTestFiles(GenTests.java:597)
	at randoop.main.GenTests.handle(GenTests.java:508)
	at randoop.main.Main.nonStaticMain(Main.java:66)
	at randoop.main.Main.main(Main.java:30)`

I feel this is because the javaagent is unable to find the class, due to the same reason as above. So, I made a jar of the project and add it to the javaagent. But since, the project has no premain, the program fails.

As far as I understood, the documentation didn't say anything about adding the classpath to bootstrap classpath or javaagent. I feel this is a genuine problem. Please revert back if I am missing something.

**Comment by markro49** [comment]
I would like to try to reproduce your problem on my system, but I can't quite figure out what you did.  I see source for test case and mock, but I wasn't sure how to proceed. Could your provide:
- exact directory layout of source, object, mock files
- exact command line used to compile program
- exact command line used to run program

Are there any additional jar files or objects I need to recreate your problem?

Thank you, Mark

**Comment by markro49** [comment]
I was finally able to build your test case (I had to create a dummy version of OrderStatus.java).  It worked fine for me.  I ran on Linux and used the latest version (4.2.5), perhaps something was fixed since 4.0.4 - almost two years ago.  From your file names, it appears you are running on Windows.  I will try the test case there to see if the behavior is any different.

**Comment by markro49** [comment]
It worked for me on Windows as well.  When we added Java 11 support in Spring 2019 there were a lot of changes to the methods involved in path searching and object loading, I'm guessing that had the effect of fixing this problem.
