### ISSUE TITLE
Parse exception when using --methodlist

### ISSUE THREAD

**Issue by robryb** [randoop/randoop#405]
**Executive summary:** 
I get a parse exception when I try to use ---methodlist on my simple "learn by doing" test case. 

**Overview:**
I am very new to Randoop. I want to see if it will help my development team with unit testing. I created a simple test case that includes a path that potentially leads to a divide by zero error. The goal is to see if Randoop can find it and somehow flag it for me.

**Details:**
I am using:
 Randoop for Java version 4.0.4.
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
CentOS running in Oracle VirtualBox (all recent downloads of stable versions) on a Windows 10 laptop that is up to date on patches.

I am having some success with randoop and I am ready to bump it up a bit. I tried using the --methodlist option using this command:

$JAVA_HOME/bin/java -ea -classpath "$JAVA_HOME/bin:$RANDOOP_JAR:." randoop.main.Main gentests --methodlist=mymeths.txt --time-limit=10

The resulting error is:

Error: parse exception thrown randoop.reflection.SignatureParseException: Class class BadDiv found, but method doDiv([int, int]) not found for signature BadDiv.doDiv(int,int)
Here are the declared methods:%n  private static void BadDiv.doDiv(int,int)
  public static void BadDiv.main(java.lang.String[])

**FILES:**
All required files will be attached. They are short so I showed them here for the convenience of the reader.

My methods file contains a single line:

```
BadDiv.doDiv(int,int)
```

My source code is:

```
import java.util.Scanner;

public class BadDiv {
  public static void main(String[] args) 
  {
    Scanner input = new Scanner (System.in);
    System.out.print("Input the first number: ");
    int num1 = input.nextInt();
    System.out.print("Input the second number: ");
    int num2 = input.nextInt();
    doDiv(num1, num2);
  }

  private static void doDiv(int start, int end) {
    for (int i = start; i<end; i++) {
      for (int j = start; j<end; j++) {
        int quotient = j / i;
        System.out.println("q: " + quotient);
      }
    }
  }
}
```
**My hunch:**
I think that I am making a mistake in the methods file, although my little example seems consistent with a line from https://randoop.github.io/randoop/manual/method_list_example.txt:

java.util.Collections.swap(java.util.List,int,int)

Notice that this example includes two ints in the parameter list, so I thought I was doing it right. 

Can someone please show me the right way?

PS, BadDiv.txt is the Java file. The interface wouldn't let me upload a .java file.
EDIT:  Used markdown improved appearance of the code.

[mymeths.txt](https://github.com/randoop/randoop/files/2303192/mymeths.txt)
[BadDiv.txt](https://github.com/randoop/randoop/files/2303197/BadDiv.txt)

**Comment by robryb** [comment]
Just found it. The member being tested must be public. 

Randoop did find my test case. It applied parameters like 
```
BadDiv.doDiv((-1), (int) 'a');
BadDiv.doDiv(0, 10);
```
So, happy days to that. I should have seen my mistake but didn't. Oh, well.

**Comment by 3rcode** [comment]
@robryb I wonder how to get methodlist format from raw source code, is there any autonomous way?

**Comment by mernst** [comment]
Please do not pollute the conversation of this issue (which is about a parse exception when using `--methodlist`) with unrelated points.

**Comment by 3rcode** [comment]
> Please do not pollute the conversation of this issue (which is about a parse exception when using `--methodlist`) with unrelated points.

sorry, I don't know the rule
