### ISSUE TITLE
Ignoring non-visible path error

### ISSUE THREAD

**Issue by krsandy** [randoop/randoop#409]
Hi,
Can anyone please help me to generate junit test cases for "Add.class" using Randoop? The java file(Add.java) is a simple program to add 2 user input numbers. I have the "Add.class" file generated after building the code. I have placed the .class file inside the folder where my randoop jar files are present.
When i try to run the gentests command

C:\Tools\Randoop>java -classpath C:\Tools\Randoop\randoop-all-4.1.0.jar randoop.main.Main gentests --testclass=Add --time-limit=30

its giving me the below error:

C:\Tools\Randoop>java -classpath C:\Tools\Randoop\randoop-all-4.1.0.jar randoop.main.Main gentests --testclass=Add --time-limit=30
Ignoring non-visible class Add specified via --classlist or --testclass.
There are no operations to test. Exiting.
Model with hashcode 519569038:
  classTypes = [java.lang.Object]
  inputTypes = []
  coveredClassesGoal = []
  classLiteralMap = {}
  annotatedTestValues = []
  contracts = randoop.test.ContractSet@6f79caec
  omitMethods = []
Operations:
  java.lang.Object.<init> : () -> java.lang.Object

------------------------------------------------------------------------------------------------------------------
Here is the program..
[Add.java]
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

class Add{
public static void main(String arng[]){
Scanner data = new Scanner(System.in);
int num1, num2;
System.out.println("Enter 1st number");
num1 = data.nextInt();
System.out.println("Enter 2nd number");
num2 = data.nextInt();
sum(num1,num2);

}
// sum method
public static void sum(int numx, int numy){
int sum=0;
sum=numx+numy;
System.out.println("Sum of 2 number:"+sum);
}
}

**Comment by krsandy** [comment]
@mernst  Can u please help me to overcome this issue?

**Comment by mernst** [comment]
You set the classpath to contain only Randoop:

> -classpath C:\Tools\Randoop\randoop-all-4.1.0.jar

You need to put Add.class on the classpath.  That is explained at the beginning of [the manual](https://randoop.github.io/randoop/manual/index.html#running_randoop).
