### ISSUE TITLE
Randoop skips methods in Interfaces in Java 8

### ISSUE THREAD

**Issue by gryan-sovrn** [randoop/randoop#415]
Tested in Randoop 4.10 Release

Randoop skips testing of Interfaces in Java 8.  With Java 8, `static` and `default` methods may be added to interfaces.  https://www.journaldev.com/2752/java-8-interface-changes-static-method-default-method

It would be helpful to be able to use Randoop to automatically generate tests for these methods instead of skipping Interfaces completely as it currently does.

**Comment by mernst** [comment]
Thanks for the suggestion.  Do you have a test case that we could use to test the feature when it is implemented?

**Comment by mernst** [comment]
I believe that Randoop version 4.2.5 fixes this.
If not, please re-open the issue.
