### ISSUE TITLE
Unable to load class "ABC" due to exception: java.lang.NoClassDefFoundError: ABC (wrong name: packagePath\ABC)

### ISSUE THREAD

**Issue by jnanesh123** [randoop/randoop#416]
Hi all,

i am getting below error when i try to generate the test for an .class file . Could you please help me on the same.

NOTE: i am trying to generate script via windows command prompt

Error:
Unable to load class "ABC" due to exception: java.lang.NoClassDefFoundError: ABC (wrong name: packagePath\ABC)

Windows Command:

Navigated to test class files folder via cmd then executed below 

java -classpath .;C:\randoop\randoop-4.1.0\randoop-4.1.0\randoop-all-4.1.0.jar randoop.main.Main gentests --testclass=ABC

**Comment by jnanesh123** [comment]
Hi ,

Please find the attached java file and also please let me know if you need more information on the same.

[TestRandoop - Copy.txt](https://github.com/randoop/randoop/files/2729471/TestRandoop.-.Copy.txt)

Error:
Error: Unable to load class "TestRandoop" due to exception: java.lang.NoClassDefFoundError: TestRandoop (wrong name: level1/level2/level3/level4/TestRandoop)

Randoop Version: randoop-4.1.0

Compiled using Eclipse: Mars 2.0

Java Version: 8

Randoop Command: C:\practice\pratciceLearning\bin\level1\level2\level3\level4>java -classpath .;C:\randoop\randoop-4.1.0\randoop-4.1.0\randoop-all-4.1.0.jar randoop.main.Main gentests --testclass=TestRandoop

**Comment by mernst** [comment]
Your classpath is wrong.  It needs the directory that contains `level1`, but you have used the directory that (I assume) contains `TestJava.class`.  Please see your Java documentation to learn how to run the `java` program and use its command-line arguments.
