### ISSUE TITLE
Regex matching in Pre-condition

### ISSUE THREAD

**Issue by devikasondhi** [randoop/randoop#417]
Hello,

I'm using Randoop-4.1.0 to generate tests for Java methods specifically dealing with structured string inputs. Could you confirm if the mentioned version has support for specifying a pre-condition in the specification file that can check if an input parameter (String type) matches a regex?
I've been trying to add something like below to my spec file but with no success:
```
"pre": [
   {
      "guard": {
        "condition": "Pattern.compile(\"^(([a-zA-Z]\\:)|(\\\\))(\\\\{1}|((\\\\{1})[^\\\\]([^/:*?<>\"|]*))+)$\").matches(fileName)",
		"description": "input should be a valid filename"
      }
    }
	],

```
I get the following error:

```
Error: Condition method did not compile: illegal escape characterillegal s
tart of expressionillegal start of expressionillegal start of expressionillegal start of expressionnot a statementunclosed string literalnot a statement
Class Declaration:
package com.google.common.io;

public class RandoopExpressionClass0 {
  public static boolean MethodNameIsIrrelevant(com.google.common.io.Files2 receiver, java.lang.String fileName) throws Throwable {
    return Pattern.compile("^(([a-zA-Z]\:)|(\\))(\\{1}|((\\{1})[^\\]([^/:*?<>"|]*))+)$").matches(fileName);
  }
}
: Compilation failed

```

I've also tried with String.matches() but with no luck. Any help/workaround would be highly appreciated. Thanks.

**Comment by devikasondhi** [comment]
Any updates on this? Am I missing on something here?

**Comment by mernst** [comment]
Sorry for the delayed response.

The cause is an error in your quoting.
In the snippet you provided, this:
```
   ...<>\"|]...
```
should have been
```
   ...<>\\"|]...
```
Note the need for an extra backslash.

I determined this by cut-and-pasting the code after the "Class Declaration:" in the output message into an IDE, which highlighted the problem.
Thank you for providing that output, which made it easy to diagnose the problem.

Your bug report also indicated the need for better diagnostics when a user-supplied condition is faulty.  Therefore, I have improved the diagnostics in this case, in commit 93c89be1.  I hope that is helpful to you and others in the future.

**Comment by devikasondhi** [comment]
Thanks for responding. Fixing the regex does not lead to the exception getting thrown now. However, now on executing Randoop on the method [com.zip](https://github.com/randoop/randoop/files/2776311/com.zip), the execution does not seem to terminate, despite using  --usethreads=true. On force termination, the test methods produced only contain wildcardclass objects being defined as follows, with an assertNotNull check on them:

`java.lang.Object obj0 = new java.lang.Object();`
`java.lang.Class<?> wildcardClass1 = obj0.getClass();`
`org.junit.Assert.assertNotNull(wildcardClass1);` 

Command used: `java -Xmx3000m -classpath PathtoRandoopjar\randoop-all-4.1.0.jar;. randoop.main.Main gentests --testclass=com.google.common.io.Files2  --specifications=fileextn.txt --junit-output-dir=./randoopOutput/fileextn3 --randomseed=1  --usethreads=true`

Note that without passing the specification txt [fileextn.txt](https://github.com/randoop/randoop/files/2776301/fileextn.txt), the execution keeps running for indefinite time, however, on force termination, I could still get some test cases being produced, though they did not comply with the expected structure of the input (hence, the need to pass the pre-condition). Is it the case that the tests produced without passing the specification file are expected to be a superset of the tests produced on passing the specification file?  Thanks for your help.

**Comment by devikasondhi** [comment]
Hello,

It seems that Randoop applies filtering based on pre-condition after the generation of test cases. Is that correct? Else if the conditions were checked in the process of input generation to generate feedback, I would have expected to get compliant input structures, which is not the case that I see from the output.

Thanks.

**Comment by mernst** [comment]
I'm sorry you are still having problems.
It seems that [your new problem](https://github.com/randoop/randoop/issues/417#issuecomment-455839351) is unrelated to this issue (#417), which is about users providing invalid regular expressions.
 * If so, could you please create a new issue to avoid confusion and prevent your new problem from being overlooked?
 * If not, could you clarify how your new problem is the same as providing invalid regular expressions?

Thanks.
