### ISSUE TITLE
Single Assert per Test Case for Maintainability

### ISSUE THREAD

**Issue by numeralnathan** [randoop/randoop#420]
The generated test cases are long and difficult to read. Instead of generating long test cases with many Assert statements in each test case, generate several test cases with 1 Assert statement per test case. This is a good practice for writing test cases. This will make the test cases short and easy to read. It will make each test case focused on testing 1 property and hence make it easy to understand.  If the test case fails, then it will be fairly obvious which property changed.  It will be easy to change the test case if the expected behavior is supposed to change.  There will be no need to waste time running minimization on the test case since it will already be minimized.  Furthermore, this opens the door to automatically naming the test cases with something useful instead of test_###... but automatic naming is for another issue.

The reason programmers use Randoop is to reduce the amount of work they have to do.  Sure automatically generating the test cases saves a lot of time, but that is only part of the cost of the test code.  The other cost of the test code is maintaining the test cases as the code under test evolves.

Version: 4.1.0
Command: `java -classpath randoop-all-4.1.0.jar;... randoop.main.Main gentests --classlist=myclasses.txt --time-limit=60`

**Comment by nathanila** [comment]
When I write test cases of this nature, I write helper methods that do repetitive work or I write parameterized tests.  This makes the tests very clear and minimize the amount of code.
