### ISSUE TITLE
Use assertEquals instead of assertTrue

### ISSUE THREAD

**Issue by numeralnathan** [randoop/randoop#421]
Currently, the generated test cases have `Assert.assertTrue` and the actual value is == to the expected value.  The code also creates a String.  The String creation consumes CPU time and will trigger GC more often.  Hence the overall performance of the tests will be lower.  Please use `Assert.assertEquals` where possible so that the String does not need to be dynamically generated.  Instead the string can be a static with the variable name (e.g. `"i3"`).

Version: 4.1.0
Command: `java -classpath randoop-all-4.1.0.jar;... randoop.main.Main gentests --classlist=myclasses.txt --time-limit=60`

**Comment by mernst** [comment]
Thanks for the idea.  This would improve the tests.

An implementation note:  This requires adding some special-case code -- not just in test code generation, but also in some tools, such as Minimize, that processes generated tests.  A search for `assertTrue` will reveal these.

**Comment by nathanila** [comment]
Perhaps you should close this issue since this is a feature request and it would clutter the bugs.

**Comment by mernst** [comment]
I'm closing this to unclutter the issue tracker.  If the test performance is an issue for other users, we can implement this feature.
