### ISSUE TITLE
Usage of pre-conditions with regex matches

### ISSUE THREAD

**Issue by devikasondhi** [randoop/randoop#448]
Hello,

This is in continuation to the issue#417/query reported before. It seems that Randoop applies filtering based on pre-condition after the generation of test cases. Is that correct? Else if the pre-conditions were checked in the process of input generation to generate feedback, I would have expected to get compliant input structures, which is not the case that I see from the output.

Thanks.

_Originally posted by @devikasondhi in https://github.com/randoop/randoop/issues/417#issuecomment-473838160_

**Comment by mernst** [comment]
I'm sorry you are having trouble.
Can you please provide a reproducible test case?  You said:

> I would have expected to get compliant input structures, which is not the case that I see from the output.

but I don't know what you expected or what you see in the output.  Clarifying that would also be helpful in diagnosing your problem.

Thanks.

**Comment by devikasondhi** [comment]
Hello,

I'm using Randoop-4.1.0 to generate tests for Java methods specifically dealing with structured string inputs. I'm interested in generating test inputs for the `getFileExtension(String fileName)` method in the `Files2` class available in [com.zip](https://github.com/randoop/randoop/files/2984501/com.zip). As the method is expected to take a filename as input, I'm passing the specification file to pass the pre-condition on the fileName argument that it should match the regex of a filename, as specified here [fileextn.txt](https://github.com/randoop/randoop/files/2984511/fileextn.txt). I'm executing randoop as follows:

Command used (on Java 8): java `-Xmx3000m -classpath PathtoRandoopjar\randoop-all-4.1.0.jar;. randoop.main.Main gentests --testclass=com.google.common.io.Files2 --specifications=fileextn.txt --junit-output-dir=./randoopOutput/fileextn3 --randomseed=1 --usethreads=true`

The execution does not seem to terminate, despite using `--usethreads=true`. On force termination, the test methods produced only contain wildcardclass objects being defined as follows, with an assertNotNull check on them:
```
java.lang.Object obj0 = new java.lang.Object();
java.lang.Class<?> wildcardClass1 = obj0.getClass();
org.junit.Assert.assertNotNull(wildcardClass1);
```

Instead of the above output, I expected the RegressionTest and Error Test files to contain testmethods with test inputs that comply with the specified pre-condition which is to take valid filename input strings. 
Let me know if you require any other detail to reproduce the problem.

I'm confused whether Randoop applies filtering based on the pre-condition after the generation of test cases or does the check happen during the generation of test strings and then passed as feedback? In other words, is it the case that the tests produced without passing the specification file are expected to be a superset of the tests produced on passing the specification file? 

Thanks for your help.

**Comment by devikasondhi** [comment]
Also sharing some extra info.:
Note that without passing the specification fileextn.txt, the execution keeps running for indefinite time, however, on force termination, I could still get some test cases being produced, though they did not comply with the expected filename structure of the input as for the below generated case (hence, the need to pass the pre-condition):

```
@Test
    public void test2() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test2");
        java.lang.String str1 = com.google.common.io.Files2.getFileExtension("hi!");
        org.junit.Assert.assertTrue("'" + str1 + "' != '" + "" + "'", str1.equals(""));
    }
```
However, on passing the specification, all I get are wildcardclass objects as described in the above reponse.

**Comment by mernst** [comment]
Thanks for clarifying your issue.  And sorry for the delay in following up; the notification fell through the cracks.

Randoop does not create random strings or primitive values.  Randoop has a small set of hard-coded primitives and strings.  Other than that, Randoop only uses the output of methods as values in tests.

You can include, as a method under test, a method that creates random values (or creates filename strings).  Its output will be used as an input to methods in your code.
