### ISSUE TITLE
Lots of duplicate inputs and outputs. Check the attached project

### ISSUE THREAD

**Issue by sbabupresidency1** [randoop/randoop#449]
**Randoop version** - 4.1.1
**OS** - Win 10
**Java** - jdk1.8.0_191
Import my project and simply execute the **"AutoUnitMain"** as Java Application.
**Concept:** Reading JSON file, creating Java class with condition and AutoGenerate JUNIT.
**Dymically created Class:** Eg: ruleBuilderScenario1.java
**Sample UnitTest** - 
 public void test025() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test025");
        com.babu.autounit.ruleBuilderScenario1 ruleBuilderScenario1_0 = new com.babu.autounit.ruleBuilderScenario1();
        java.lang.Class<?> wildcardClass1 = ruleBuilderScenario1_0.getClass();
        java.lang.Class<?> wildcardClass2 = ruleBuilderScenario1_0.getClass();
        java.lang.String str3 = ruleBuilderScenario1_0.getLocation();
        **ruleBuilderScenario1_0.setAge((int) '#');**
        **ruleBuilderScenario1_0.setAge(20);**
        java.lang.String str8 = ruleBuilderScenario1_0.getGender();
        org.junit.Assert.assertNotNull(wildcardClass1);
        org.junit.Assert.assertNotNull(wildcardClass2);
        org.junit.Assert.assertNull(str3);
        org.junit.Assert.assertNull(str8);
**Expected:** No perfect combination for my condition.

No Need do anything. Simply import and add Randoop jars. JDK1.8 that's all. Run "**AutoUnitMain**". 

[AutoRuleGenerator (2).zip](https://github.com/randoop/randoop/files/2983159/AutoRuleGenerator.2.zip)

**Comment by mernst** [comment]
I'm sorry you are having trouble.
I don't understand this text:

> Expected: No perfect combination for my condition.

I think that maybe you want Randoop to recognize that calling `setAge` twice in a row has no effect and it could just use the second of the two calls.

In other cases, multiple calls do have an effect; for example, calling `List.add` twice is different than calling it just once.

Randoop does not currently have an analysis that tells it the effect of each method call.
If you wished to contribute one, that would be helpful and would improve Randoop's output.

In the meanwhile, if a test fails, a user can [minimize](https://randoop.github.io/randoop/manual/index.html#minimize) the test, which eliminates all unnecessary calls.

**Comment by mernst** [comment]
I'm closing this because the problem was unclear and the reporter did not respond.
