### ISSUE TITLE
Unable to load class "MainClass" due to exception

### ISSUE THREAD

**Issue by ff2084** [randoop/randoop#450]
The exact error I'm getting is : 
Error: Unable to load class "MainClass" due to exception: java.lang.NoClassDefFoundError: MainClass (wrong name: thiagodnf/sootparser/example/grocery/MainClass)

Included in the Zip is the class files, which I have located in a file path of: `C:\Eclipse\Workspaces\Refactor\sootparser-master\sootparser-example-grocery\target\classes\thiagodnf\sootparser\example\grocery`

The command I am attempting to run is: **C:\Eclipse\randoop>**```
java -Xmx3000m -classpath C:\Eclipse\Workspaces\Refactor\soot
parser-master\sootparser-example-grocery\target\classes\thiagodnf\sootparser\exa
mple\grocery;C:/Eclipse/randoop/randoop-all-4.1.1.jar randoop.main.Main gentests
 --testclass=MainClass```

[grocery.zip](https://github.com/randoop/randoop/files/2998400/grocery.zip)

The source code is stored at this path:` C:\Eclipse\Workspaces\Refactor\sootparser-master\sootparser-example-grocery\src\main\java\thiagodnf\sootparser\example\grocery`

And is included below with the zip file slightly renamed so as not to be confusing

[groceryJava.zip](https://github.com/randoop/randoop/files/2998403/groceryJava.zip)

The short term I would like it to run against MainClass, in the long run i'll need to do a class file, and run it against all the classes in the different modules. 

Thanks for anything you can do to help

**Comment by mernst** [comment]
The error message 

> java.lang.NoClassDefFoundError: MainClass (wrong name: thiagodnf/sootparser/example/grocery/MainClass)

indicates that your program does not include a class named `MainClass`.  It does include a class named 
`thiagodnf.sootparser.example.grocery.MainClass`.

The [documentation for the `--testclass` command-line option](https://randoop.github.io/randoop/manual/index.html#option:testclass) says, "The **fully-qualified** raw name of a class to test".
If you provide the correct class name, then Randoop should work.
