### ISSUE TITLE
"this" should be "type"

### ISSUE THREAD

**Issue by smillst** [randoop/randoop#463]
At this line: 
https://github.com/randoop/randoop/blob/a460df97fde401646c58001d241d912f10464ea5/src/main/java/randoop/types/Type.java#L521

"this" should actually be type.

and again a few lines down:
```
 return this.getRuntimeClass().getName().compareTo(this.getRuntimeClass().getName());
```

**Comment by mernst** [comment]
Thanks for noticing this blunder!
