### ISSUE TITLE
Test generation should stop based on --outputlimit command-line argument

### ISSUE THREAD

**Issue by mernst** [randoop/randoop#58]
Test generation should stop when there would be more than --outputlimit generated tests.  Currently only --inputlimit and --timelimit have any effect.

This makes some common tasks that a user might wish to perform unnecesarily difficult or inefficient.  For example, suppose a user wishes to generate 5000 tests.  The user needs to either supply a really large value for --timelimit and --inputlimit, and as a result many tests might be discarded.

This may not be trivial, because every time a new test is generated, it may cause other tests not to be output (even though they would have been in the absence of the new test).

**Comment by bjkeller** [comment]
In v2.1.0, the generation loop now stops on the --outputlimit value. However, the filtering during generation does not remove subsumed subsequences, which are removed when the output sequences are retrieved.  This means that generation may stop before the actual output (with subsumed subsequences removed) reaches the --outputlimit.
