### ISSUE TITLE
Implement --omit-classes and --omit-classes-file command-line arguments

### ISSUE THREAD

**Issue by Ahmedfir** [randoop/randoop#599]
I am trying to omit some classes. It didn't work. I checked the code and apparently the attributes `omit_classes_file` and `randoop.main.GenInputsAbstract#omit_classes` are never used. Do you have any other alternative to omit a class?
Thank you in advance for your time and support

**Comment by mernst** [comment]
You are right.  That feature was never implemented.  Sorry about that.  I'll remove them from the manual, and we can implement the feature if there is demand for it.

**Comment by mernst** [comment]
@Ahmedfir I have made a [pull request](#649) that implements this feature.
If you have time, could you try it out?

**Comment by Ahmedfir** [comment]
Yes sure.
