### ISSUE TITLE
Support For Custom Classes

### ISSUE THREAD

**Issue by RONNCC** [randoop/randoop#600]
(Feature Request)

How would one add support for non-primitive constructs in randoop?

e.g. to test the following
```
public IntPair addIntPairs(IntPair p1, IntPair p2) // class IntPair { int a; int b }
{ return IntPair { p1.1 + p2.2, p1.2 + p2.2 }  }
```

This is slightly different from providing another class in the myclasses.txt that can be built and then using that output into this function since that would also cause it's various public functions to be permutated which is not wanted when testing edge cases for the above function.

The particular use case here is testing methods that take as arguments autogenerated classes when testing RPC functions that take 'richer' types.

One could instead provide a 'generator' class with a series of generators. eg. But I presume there's a more idiomatic way? 

```
public IntPair generateIntPair(int a, int b) { return new IntPair(a,b); } 
```

---

Randoop V4.2
Java: java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

**Comment by mernst** [comment]
I'm sorry you are having trouble.

Randoop already supports non-primitive constructs and user-defined classes.

I'm not sure how to interpret your remark "which is not wanted", and why command-line arguments such as [--omit-methods](https://randoop.github.io/randoop/manual/index.html#option:omitmethods) do not achieve what you want.

As requested in the issue template, can you provide a concrete execution of Randoop and indicate how you wish that its output were different?  (And why current Randoop command-line arguments cannot achieve that.)  I think that will make your use case more clear, and will enable us to help you.

Thanks!

**Comment by mernst** [comment]
I'm closing this because the reporter did not give the requested details.
