### ISSUE TITLE
Support for Custom Classes

### ISSUE THREAD

**Issue by Kaustavd** [randoop/randoop#620]
In case of testing custom classes I am getting only default test case having null value which is being generated from the line
**TypedOperation st = TypedOperation.createNullOrZeroInitializationForType(inputType);**

This is my sample method

public static boolean isCorrectAmount(InputClass inputClass) {
    double transactionAmount  = inputClass.getTransactionAmount();
    if(transactionAmount > 50) {
      return true;
    } else {
      return false;
    }
  }
 Running randoop on same methid I am getting only one test case having

 @Test
    public void test1() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test1");
        com.flipkart.cp.convert.europa.datamodels.oms.payment.data.v3.DecryptedPGResponseData decryptedPGResponseData0 = null;
        // The following exception was thrown during execution in test generation
        try {
            boolean boolean1 = com.flipkart.cp.convert.europa.europautils.AmountUtils.isCorrectAmount(decryptedPGResponseData0);
            org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException; message: null");
        } catch (java.lang.NullPointerException e) {
        // Expected exception.
        }
    }

but when I change the signature of the function to 

public static boolean isCorrectAmount(**double transactionAmount**) {
    if(transactionAmount > 50) {
      return true;
    } else {
      return false;
    }
  }

I am getting test cases on variety of input value in test cases

Randoop version being used is 4.2.0

Am I missing something here?

**Comment by Kaustavd** [comment]
**Snippet of Code under test:**
==========================
public class AmountUtils {

  public static boolean isCorrectAmount(InputClass inputClass) {
    double transactionAmount  = inputClass.getTransactionAmount();
    if(transactionAmount > 50) {
      return true;
    } else {
      return false;
    }
  }

  public static boolean isCorrectAmount(double transactionAmount) {
    if(transactionAmount > 50) {
      return true;
    } else {
      return false;
    }
  }
}

public class InputClass {
  double transactionAmount;
  double amount;

  public double getTransactionAmount() {
    return transactionAmount;
  }

  public void setTransactionAmount(final double transactionAmount) {
    this.transactionAmount = transactionAmount;
  }

  public double getAmount() {
    return amount;
  }

  public void setAmount(final double amount) {
    this.amount = amount;
  }
}

**First Command Run with Customized class as input argument** 
===================================================
 java -Xmx3000m -cp /Users/kaustav.das/Downloads/randoop-4.2.0/randoop-all-4.2.0.jar:/Users/kaustav.das/flipkart/github/test/target/target-0.1-jar-with-dependencies.jar:/Users/kaustav.das/flipkart/github/test/utils/target/target.jar randoop.main.Main gentests --methodlist=/Users/kaustav.das/methodTobeTested1.txt --output-limit=100

**Content of /Users/kaustav.das/methodTobeTested1.txt**
=============================================
com.test.utils.AmountUtils.isCorrectAmount(com.test.utils.InputClass)

**Output**
============

import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class RegressionTest0 {

    public static boolean debug = false;

    @Test
    public void test1() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test1");
        com.test.utils.InputClass inputClass0 = null;
        // The following exception was thrown during execution in test generation
        try {
            boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount(inputClass0);
            org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException; message: null");
        } catch (java.lang.NullPointerException e) {
        // Expected exception.
        }
    }
}

**Second Command Run with primitive(double) as input argument** 
===================================================
 java -Xmx3000m -cp /Users/kaustav.das/Downloads/randoop-4.2.0/randoop-all-4.2.0.jar:/Users/kaustav.das/flipkart/github/test/target/target-0.1-jar-with-dependencies.jar:/Users/kaustav.das/flipkart/github/test/utils/target/target.jar randoop.main.Main gentests --methodlist=/Users/kaustav.das/methodTobeTested2.txt --output-limit=100

**Content of /Users/kaustav.das/methodTobeTested2.txt**
=============================================
com.test.utils.AmountUtils.isCorrectAmount(double)

**Output**
=============

import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class RegressionTest0 {

    public static boolean debug = false;

    @Test
    public void test01() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test01");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount((double) 10);
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + false + "'", boolean1 == false);
    }

    @Test
    public void test02() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test02");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount((double) (byte) 0);
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + false + "'", boolean1 == false);
    }

    @Test
    public void test03() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test03");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount((double) 0);
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + false + "'", boolean1 == false);
    }

    @Test
    public void test04() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test04");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount(0.0d);
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + false + "'", boolean1 == false);
    }

    @Test
    public void test05() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test05");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount((double) (short) 0);
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + false + "'", boolean1 == false);
    }

    @Test
    public void test06() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test06");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount((double) 'a');
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + true + "'", boolean1 == true);
    }

    @Test
    public void test07() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test07");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount(100.0d);
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + true + "'", boolean1 == true);
    }

    @Test
    public void test08() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test08");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount((double) (-1.0f));
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + false + "'", boolean1 == false);
    }

    @Test
    public void test09() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test09");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount((double) (short) 100);
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + true + "'", boolean1 == true);
    }

    @Test
    public void test10() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test10");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount((double) '4');
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + true + "'", boolean1 == true);
    }

    @Test
    public void test11() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test11");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount((-1.0d));
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + false + "'", boolean1 == false);
    }

    @Test
    public void test12() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test12");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount((double) (short) -1);
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + false + "'", boolean1 == false);
    }

    @Test
    public void test13() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test13");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount((double) (-1L));
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + false + "'", boolean1 == false);
    }

    @Test
    public void test14() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test14");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount((double) 10L);
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + false + "'", boolean1 == false);
    }

    @Test
    public void test15() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test15");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount((double) 100);
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + true + "'", boolean1 == true);
    }

    @Test
    public void test16() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test16");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount((double) 1);
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + false + "'", boolean1 == false);
    }

    @Test
    public void test17() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test17");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount((double) ' ');
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + false + "'", boolean1 == false);
    }

    @Test
    public void test18() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test18");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount(1.0d);
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + false + "'", boolean1 == false);
    }

    @Test
    public void test19() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test19");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount((double) 0L);
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + false + "'", boolean1 == false);
    }

    @Test
    public void test20() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test20");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount((double) 100L);
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + true + "'", boolean1 == true);
    }

    @Test
    public void test21() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test21");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount((double) 0.0f);
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + false + "'", boolean1 == false);
    }

    @Test
    public void test22() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test22");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount((double) (byte) -1);
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + false + "'", boolean1 == false);
    }

    @Test
    public void test23() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test23");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount((double) 1L);
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + false + "'", boolean1 == false);
    }

    @Test
    public void test24() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test24");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount((double) (-1));
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + false + "'", boolean1 == false);
    }

    @Test
    public void test25() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test25");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount((double) (byte) 100);
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + true + "'", boolean1 == true);
    }

    @Test
    public void test26() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test26");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount((double) 100.0f);
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + true + "'", boolean1 == true);
    }

    @Test
    public void test27() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test27");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount((double) (byte) 1);
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + false + "'", boolean1 == false);
    }

    @Test
    public void test28() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test28");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount((double) (byte) 10);
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + false + "'", boolean1 == false);
    }

    @Test
    public void test29() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test29");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount((double) 10.0f);
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + false + "'", boolean1 == false);
    }

    @Test
    public void test30() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test30");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount((double) '#');
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + false + "'", boolean1 == false);
    }

    @Test
    public void test31() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test31");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount((double) (short) 10);
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + false + "'", boolean1 == false);
    }

    @Test
    public void test32() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test32");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount((double) (short) 1);
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + false + "'", boolean1 == false);
    }

    @Test
    public void test33() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test33");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount(10.0d);
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + false + "'", boolean1 == false);
    }

    @Test
    public void test34() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test34");
        boolean boolean1 = com.test.utils.AmountUtils.isCorrectAmount((double) 1.0f);
        // Regression assertion (captures the current behavior of the code)
        org.junit.Assert.assertTrue("'" + boolean1 + "' != '" + false + "'", boolean1 == false);
    }
}

**Comment by Kaustavd** [comment]
@mernst  Did you get a chance to look into this?

**Comment by mernst** [comment]
Thank you for the full bug report; that made the problem clear.

You have told Randoop to never call any method other than `com.test.utils.AmountUtils.isCorrectAmount(com.test.utils.InputClass)`.  In particular, you have told it not to call any method that creates an `InputClass` object.  Therefore, Randoop cannot create an argument for the method `isCorrectAmount`.

https://randoop.github.io/randoop/manual/#specifying-methods says:

> Randoop only invokes a method or constructor M if all of the following are true:
> M is declared in a class that is named by --testclass, --testjar, or --classlist, or M is a member named by --methodlist.

A few sentences later, that section says:

> The methods under test must include not only the methods whose results you wish to appear in an assert statement, but also methods that a test may need to call in order to set up state or create argument values. All of those methods are also being implicitly tested by the assert statement.

This is also discussed at the beginning of the "Randoop does not create enough tests, or creates no tests" section of the "Troubleshooting" chapter of the manual:
https://randoop.github.io/randoop/manual/#not-enough-tests-created


Is there anything we can change to make this information more obvious?
