### ISSUE TITLE
How to generate different values for Enum attribute

### ISSUE THREAD

**Issue by Kaustavd** [randoop/randoop#623]
One of my class has  primitive attribute and enum attribute. As per documentation primitives are selected from given seed defined https://randoop.github.io/randoop/manual/#primitives. In case of enum attribute(Constants) I am always getting null

Sample Code snippet under test

public class InnerClass {
    private  double transactionAmount;
    private  double amount;
    private Constants constants;

    public InnerClass() {
    }

    public InnerClass(double transactionAmount, double amount, Constants constants) {
        this.transactionAmount = transactionAmount;
        this.amount = amount;
        this.constants = constants;
    }

    public double getTransactionAmount() {
        return transactionAmount;
    }

    public void setTransactionAmount(double transactionAmount) {
        this.transactionAmount = transactionAmount;
    }

    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    public Constants getConstants() {
        return constants;
    }

    public void setConstants(Constants constants) {
        this.constants = constants;
    }
}

public enum Constants {
    ONE,
    TWO,
    THREE
}

import javax.validation.constraints.NotNull;

public class A {
  private int value;

  A(instrument.testcase.B b) {
    this.value = b.getValue();
  }

  public int getValue() {
    return value;
  }

  @Override
  public String toString() {
    return "a(" + value + ")";
  }

  public static boolean isCorrectAmount(@NotNull InnerClass innerClass) {
    double transactionAmount  = innerClass.getTransactionAmount();
    if(transactionAmount > 50) {
      return true;
    } else {
      return false;
    }
  }

}

Commands Run:
java -Xmx3000m -cp /Users/kaustav.das/Downloads/randoop-4.2.0/randoop-all-4.2.0.jar:/Users/kaustav.das/flipkart/github/test/target/target-0.1-jar-with-dependencies.jar:/Users/kaustav.das/flipkart/github/test/utils/target/target.jar randoop.main.Main gentests --methodlist=/Users/kaustav.das/methodTobeTested1.txt --output-limit=100

Content of /Users/kaustav.das/methodTobeTested1.txt
instrument.testcase.A.isCorrectAmount(instrument.testcase.InnerClass)
instrument.testcase.InnerClass(double, double, instrument.testcase.Constants)

**Comment by mernst** [comment]
@Kaustavd Thanks for the bug report.

Your code does not compile for me.  I get the following output from javac:
```
A.java:4: error: package instrument.testcase does not exist
  A(instrument.testcase.B b) {
                       ^
A.java:12: error: cannot find symbol
  @override
   ^
  symbol:   class override
  location: class A
2 errors
```

I don't know whether the A constructor that takes a B is important.  Could you please correct the code?
It might also help to include all the commands to run, which includes a `javac` command.

PS:  I suggest that you surround your code with triple backquotes so that its formatting is preserved in the bug report.  See the "code" examples in the [GitHub Markdown guide](https://guides.github.com/features/mastering-markdown/).

**Comment by Kaustavd** [comment]
Thanks for the suggestions

Sharing details again

Sample Code snippet under test
InnerClass.java
```
package instrument.testcase;

public class InnerClass {
    private  double transactionAmount;
    private  double amount;
    private Constants constants;


    public InnerClass() {
    }

    public InnerClass(double transactionAmount, double amount, Constants constants) {
        this.transactionAmount = transactionAmount;
        this.amount = amount;
        this.constants = constants;
    }

    public double getTransactionAmount() {
        return transactionAmount;
    }

    public void setTransactionAmount(double transactionAmount) {
        this.transactionAmount = transactionAmount;
    }

    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    public Constants getConstants() {
        return constants;
    }

    public void setConstants(Constants constants) {
        this.constants = constants;
    }
}
```

Constants.java

```
package instrument.testcase;
public enum Constants {
    ONE,
    TWO,
    THREE
}
```
A.java

```
package instrument.testcase;
import javax.validation.constraints.NotNull;

public class A {
  private int value;

  A(instrument.testcase.B b) {
    this.value = b.getValue();
  }

  public int getValue() {
    return value;
  }

  @Override
  public String toString() {
    return "a(" + value + ")";
  }


  public static boolean isCorrectAmount(@NotNull InnerClass innerClass) {
    double transactionAmount  = innerClass.getTransactionAmount();
    if(transactionAmount > 50) {
      return true;
    } else {
      return false;
    }
  }

}
```
Commands Run:
javac A.java InnerClass.java Constants.java 
jar cvf target.jar A.class InnerClass.class Constants.class

java -Xmx3000m -cp /Users/kaustav.das/Downloads/randoop-4.2.0/randoop-all-4.2.0.jar:target.jar randoop.main.Main gentests --methodlist=/Users/kaustav.das/methodTobeTested1.txt --output-limit=100

Content of /Users/kaustav.das/methodTobeTested1.txt
instrument.testcase.A.isCorrectAmount(instrument.testcase.InnerClass)
instrument.testcase.InnerClass(double, double, instrument.testcase.Constants)

**Comment by mernst** [comment]
Unfortunately, this still does not compile (that is, the first line `javac A.java InnerClass.java Constants.java` fails) for the same reason as before:  the
```
A(instrument.testcase.B b) {
```
line in file A.java.  It uses a class `instrument.testcase.B`, but you have not provided a definition of that class.

It also doesn't compile because of the use of a `@NotNull` annotation, but I could fix that by removing the use and import of `NotNull`.

Could you please provide a complete set of files and a working set of instructions?
Then we will be able to help you.

**Comment by Kaustavd** [comment]
My bad, sharing correct code


Sample Code snippet under test
InnerClass.java
```
package instrument.testcase;

public class InnerClass {
    private  double transactionAmount;
    private  double amount;
    private Constants constants;


    public InnerClass() {
    }

    public InnerClass(double transactionAmount, double amount, Constants constants) {
        this.transactionAmount = transactionAmount;
        this.amount = amount;
        this.constants = constants;
    }

    public double getTransactionAmount() {
        return transactionAmount;
    }

    public void setTransactionAmount(double transactionAmount) {
        this.transactionAmount = transactionAmount;
    }

    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    public Constants getConstants() {
        return constants;
    }

    public void setConstants(Constants constants) {
        this.constants = constants;
    }
}
```

Constants.java

```
package instrument.testcase;
public enum Constants {
    ONE,
    TWO,
    THREE
}
```
A.java

```
package instrument.testcase;

public class A {
  private int value;

  public int getValue() {
    return value;
  }

  @Override
  public String toString() {
    return "a(" + value + ")";
  }


  public static boolean isCorrectAmount(InnerClass innerClass) {
    double transactionAmount  = innerClass.getTransactionAmount();
    if(transactionAmount > 50) {
      return true;
    } else {
      return false;
    }
  }

}
```
Commands Run:
javac A.java InnerClass.java Constants.java 
jar cvf target.jar A.class InnerClass.class Constants.class

java -Xmx3000m -cp /Users/kaustav.das/Downloads/randoop-4.2.0/randoop-all-4.2.0.jar:target.jar randoop.main.Main gentests --methodlist=/Users/kaustav.das/methodTobeTested1.txt --output-limit=100

Content of /Users/kaustav.das/methodTobeTested1.txt
instrument.testcase.A.isCorrectAmount(instrument.testcase.InnerClass)
instrument.testcase.InnerClass(double, double, instrument.testcase.Constants)

**Comment by mernst** [comment]
Thank you for correcting the code.  I am able to compile it.

The problem is exactly the same as in #620, which I answered for you a few days ago.  In particular, your `methodTobeTested1.txt` does not permit Randoop to create any values of type `Constant`.

Why are you using the `--methodlist` command-line argument?  It is an uncommon and error-prone option.  If I change your command to:

java -Xmx3000m -cp /Users/kaustav.das/Downloads/randoop-4.2.0/randoop-all-4.2.0.jar:target.jar randoop.main.Main gentests **--testjar=target.jar** --output-limit=100

then Randoop uses values like `Constant.ONE` in its tests.

**Comment by Kaustavd** [comment]
While running the command I am getting

ETC02Y95DPJG5H:randoop kaustav.das$ java -Xmx3000m -cp /Users/kaustav.das/Downloads/randoop-4.2.0/randoop-all-4.2.0.jar:target.jar randoop.main.Main gentests --testjar=target.jar --output-limit=100

Throwable thrown while handling command: java.lang.NoClassDefFoundError: src/coveredTest/java/instrument/testcase/A (wrong name: instrument/testcase/A)
java.lang.NoClassDefFoundError: src/coveredTest/java/instrument/testcase/A (wrong name: instrument/testcase/A)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at randoop.main.GenInputsAbstract.getClassnamesFromJarFile(GenInputsAbstract.java:974)
	at randoop.main.GenInputsAbstract.getClassnamesFromArgs(GenInputsAbstract.java:939)
	at randoop.main.GenTests.handle(GenTests.java:236)
	at randoop.main.Main.nonStaticMain(Main.java:66)
	at randoop.main.Main.main(Main.java:30)

**Comment by mernst** [comment]
@Kaustavd That looks like a classpath problem.
You still haven't ever provided a complete, reproducible set of instructions (such as saying what directory to run commands from; are you running your commands inside the Randoop repository or distribution for some reason?), so unfortunately I cannot help without that information.
I removed the `package` statements from your files before I ran my commands, and then I was able to run them.  But I don't know what you are doing on your machine.

**Comment by Kaustavd** [comment]
@mernst Excuse for reporting issues without enough information. 
Please find my inline answers.
are you running your commands inside the Randoop repository or distribution for some reason?)
 >>>Yes, I was running commands inside rundoop repository as I was exploring existing test cases of randoop. 



I removed the package statements from your files before I ran my commands, and then I was able to run them.
>>>By the way removing package statement also didnt help me. 


But I don't know what you are doing on your machine.
>>> **working directory**: /Users/kaustav.das/flipkart/github/randoop
**Commands:**
 1>javac src/coveredTest/java/instrument/testcase/A.java src/coveredTest/java/instrument/testcase/InnerClass.java src/coveredTest/java/instrument/testcase/Constants.java 
2> jar cvf target.jar src/coveredTest/java/instrument/testcase/A.class src/coveredTest/java/instrument/testcase/InnerClass.class src/coveredTest/java/instrument/testcase/Constants.class 
3>  java -Xmx3000m -cp /Users/kaustav.das/Downloads/randoop-4.2.0/randoop-all-4.2.0.jar:target.jar randoop.main.Main gentests --testjar=target.jar --output-limit=100

**Error:**
Throwable thrown while handling command: java.lang.NoClassDefFoundError: src/coveredTest/java/instrument/testcase/A (wrong name: A)
java.lang.NoClassDefFoundError: src/coveredTest/java/instrument/testcase/A (wrong name: A)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at randoop.main.GenInputsAbstract.getClassnamesFromJarFile(GenInputsAbstract.java:974)
        at randoop.main.GenInputsAbstract.getClassnamesFromArgs(GenInputsAbstract.java:939)
        at randoop.main.GenTests.handle(GenTests.java:236)
        at randoop.main.Main.nonStaticMain(Main.java:66)
        at randoop.main.Main.main(Main.java:30)

Randoop failed.
No sequences generated.


Why are you using the --methodlist command-line argument? It is an uncommon and error-prone option. If I change your command to
>>> Reason of putting methodList instead of testjar was I want test cases for only for method containing business logic, not constructor classes,

**Comment by mernst** [comment]
> > > > **working directory**: /Users/kaustav.das/flipkart/github/randoop

Sorry, but I need to knowing exactly what is in that directory.  Without that information, I cannot reproduce your exact problem.

Can you give a set of instructions that create a brand-new, empty directory and that put all the files in the right places to reproduce your problem?  The best format for the instructions is a list of commands that can be cut-and-pasted into a shell.  This directory should not be within Randoop itself.

> are you running your commands inside the Randoop repository or distribution for some reason?)
> 
> > > > Yes, I was running commands inside rundoop repository as I was exploring existing test cases of randoop.

Can you explain "exploring existing test cases of Randoop"?  Your tests use a top-level file named `InnerClass.java`, but I don't see such a file in Randoop, so I don't see that you are reproducing something in Randoop's test suite.

> Why are you using the --methodlist command-line argument? It is an uncommon and error-prone option. If I change your command to
> 
> > > > Reason of putting methodList instead of testjar was I want test cases for only for method containing business logic, not constructor classes,

That is *not* what `--methodList` is for.

Have you tried `--require-covered-classes` or `--require-classname-in-test`?  Those might be better matches to your use case.
