### ISSUE TITLE
--methodlist does not parse type parameters

### ISSUE THREAD

**Issue by andrewhabib** [randoop/randoop#627]
Hi, 

Randoop version: latest: 4.2.1
java: openjdk version "1.8.0_222"
os: Ubuntu 18.04.3 LTS

I am trying to generate tests for methods with generic types using the --methodlist argument.
I get the `Could not parse signature` ... errors on the following examples from apache commons-lang3:

For instance, in the following class
```
public class MutableTriple<L, M, R> extends Triple<L, M, R> { ...
```
declared in package  `org.apache.commons.lang3.tuple`, 

I am trying to specify the following methods in the input file to --methodlist.

Example 1: 
--------------
method:
```
    public static <L, M, R> MutableTriple<L, M, R> of(final L left, final M middle, final R right) {
        return new MutableTriple<L, M, R>(left, middle, right);
    }
```
where the signature I pass to randoop is:
```
<L,M,R> org.apache.commons.lang3.tuple.MutableTriple.of(L,M,R)
```

Example 2:
--------------
method:
```
    public void setLeft(final L left) {
        this.left = left;
    }
```
where the signature I pass to randoop is:
```
org.apache.commons.lang3.tuple.MutableTriple.setLeft(L)
```

Am I passing the wrong signature or may be Randoop does not support signatures like this?

**Comment by mernst** [comment]
The [`--methodlist` documentation](https://randoop.github.io/randoop/manual/#option:methodlist) says "each given as a [fully-qualified signature](https://randoop.github.io/randoop/manual/#fully-qualified-signature) on a separate line.
The link to [fully-qualified signature](https://randoop.github.io/randoop/manual/#fully-qualified-signature) says "argument-list is a comma-separated list of fully-qualified Java raw types, without spaces."

Recall that a raw type does not contain type parameters.  Compared to a regular type, it removes type parameter declarations such as `<T>`, and it and replaces any use of a type parameter by its upper bound (which is `Object` in your examples).

**Comment by andrewhabib** [comment]
Yes right!

Totally forgot type erasure! Thank you for the quick answer.

Closing ...
