### ISSUE TITLE
Fix generated test cases' names

### ISSUE THREAD

**Issue by DavidSUN2** [randoop/randoop#631]
Hi, 
I run gentests using the command below: 
`java -classpath E:\randoop-4.2.1\bin;E:\randoop-4.2.1\randoop-all-4.2.1.jar randoop.main.Main gentests --testclass=org.apache.commons.lang3.CharEncoding --regression-test-basename=CharEncoding --junit-package-name=CharEncoding --time-limit=60 --junit-output-dir=E:\randoop-4.2.1\test20`
I have fixed the package's name and regression-test-basename as CharEncoding, but I also want to fix the generated testcases' names as CharEncoding. I have checked the generated test cases' names and they all start from test and plus number. So, how should I change the command to fix the generated test cases' names starting from CharEncoding? I have read through the Randoop manual but I still cannot figure it out. Could you please give me some hints? Thanks

**Comment by mernst** [comment]
There is not currently a way to do this.

The test method names are controlled by variable [`TEST_METHOD_NAME_PREFIX`](https://github.com/randoop/randoop/blob/master/src/main/java/randoop/main/GenTests.java#L134).  You could introduce a new command-line option to control this.  You would want to mimic the `--junit-package-name=CharEncoding` command-line option and the variable `GenInputsAbstract.junit_package_name` that it controls.  We would be happy to consider a pull request that did this.

**Comment by mernst** [comment]
I'm closing this because it is a feature request.  We still welcome a pull request that follows the instructions I gave.
