### ISSUE TITLE
Generated tests are not as expected

### ISSUE THREAD

**Issue by feeroz123** [randoop/randoop#632]
Hi,

I am new to Randoop. I wrote a simple Java program and was able to execute the Randoop jar after some trials. I got the output tests which do not test the functionality written in Java file. Please help me understand how it works and if I made mistakes.

The version of Randoop, the output of `java -version`, and the operating system version.
```
Randoop Version = 4.2.1

D:\Softwares\randoop-4.2.1>java -version
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)
```

The commands you ran, so that we can paste them into a command terminal.  Please don't omit any steps, including installing software or setting environment variables.

My _testRandoop.java_ file in present in _D:\Softwares\randoop-4.2.1\test\_

```
D:\Softwares\randoop-4.2.1>cd test/
D:\Softwares\randoop-4.2.1\test>javac testRandoop.java
D:\Softwares\randoop-4.2.1>java -classpath "C:/Program Files/Java/jdk1.8.0_221/lib/";randoop-all-4.2.1.jar;test/ randoop.main.Main gentests --testclass=testRandoop
```

A transcript of all the output (as text, not a screenshot).
Last few lines are as below:

```
Progress update: steps=47053000, test inputs generated=4, failing inputs=0      (Fri Dec 06 15:40:17 IST 2019     62MB used)
Progress update: steps=47053287, test inputs generated=4, failing inputs=0      (Fri Dec 06 15:40:17 IST 2019     62MB used)
Normal method executions: 27
Exceptional method executions: 0

Average method execution time (normal termination):      0.00476
Average method execution time (exceptional termination): NaN
Approximate memory usage 62MB
Explorer = ForwardGenerator(steps: 47053287, null steps: 47053283, num_sequences_generated: 4;
    allSequences: 4, regresson seqs: 3, error seqs: 0=0=0, invalid seqs: 0, subsumed_sequences: 0, num_failed_output_test: 1;
    runtimePrimitivesSeen:38)

No error-revealing tests to output

About to look for failing assertions in 2 regression sequences.

Regression test output:
Regression test count: 2
Writing regression JUnit tests...
Created file D:\Softwares\randoop-4.2.1\RegressionTest0.java
Created file D:\Softwares\randoop-4.2.1\RegressionTest.java
Wrote regression JUnit tests.
About to look for flaky methods.

Invalid tests generated: 0
```

The result files are attached.
[Result.zip](https://github.com/randoop/randoop/files/3931695/Result.zip)

What you expected to happen instead.
After reading the description of Randoop, I was happy that I can use it to 'generate' unit tests for complex programs in my office. But when I look at the result files, I thought it could wrie tests which would actually test the functionality. Not just check if the class file returned is Not null.
I think I am missing something.

Files that are used by the commands you ran.
Attached here:
[test.zip](https://github.com/randoop/randoop/files/3931707/test.zip)

Please assist in getting proper results if the Randoop jar is supposed to create actual unit tests.

Thank you.

**Comment by mernst** [comment]
I'm sorry you are having trouble.  Could you answer a couple questions to help us understand your problem?

1. Have you followed the instructions in the [Randoop does not create enough tests, or creates no tests](https://randoop.github.io/randoop/manual/index.html#not-enough-tests-created) section of the manual?

2. Can you give an example of a test that you hoped Randoop would produce?

**Comment by feeroz123** [comment]
Hi,

1. No, I did not see this section before. I am getting the test files
generated with test methods present in it, but no actual test being
performed. I am going through the instructions now and I see that I might
need to improvise my java code for it to get easily understood by Randoop.
Thanks for pointing me to this section.
2. I was expecting to see some actual tests generated by Randoop. Like
creating some dummy input values (for different scenarios) and run the
method with those dummy values and verifying the output, like I would do as
a Unit tester. And may be generate some mocks in case of inter-dependent
class files. May be my expectations are high and unrealistic!

------------------------------
Regards,

Feeroz Alam

**Comment by mernst** [comment]
I'm glad you now have a place to start.

1. Let us know the outcome of your investigation, or if you have questions.

2. I asked for a concrete example of a test.  That would still be helpful to understand your expectations.

**Comment by mernst** [comment]
I'm closing this because the reporter did not provide details.
