### ISSUE TITLE
Not able to generate junits for jar file.

### ISSUE THREAD

**Issue by coolash-NullpointerException** [randoop/randoop#642]
I am trying to generate error tests junits for springboot microservice jar , but randoop is not able to find the jar file. I am using --testjar command. Kindly give me a solution.

**Comment by mernst** [comment]
We will do our best to give you a solution.  To enable that, please give us a proper bug report.  The text you deleted in order to write your two short sentences told you how to do it.  The Randoop Manual also tells you how to do it.

**Comment by mernst** [comment]
I'm closing this because the reporter did not provide sufficient details.
