### ISSUE TITLE
accessibleObject is null when testing x.y.hashCode()

### ISSUE THREAD

**Issue by andrewhabib** [randoop/randoop#645]
Hi,

Current configs:

Randoop version: latest: 4.2.1
java version "1.8.0_171"
os: Ubuntu 18.04.3 LTS

I am trying to generate tests for different methods from apache commons libraries such as collections4 and lang3. 

When using the --methodlist option, Randoop does not accept any x.y.hashCode() method such as:
- ```org.apache.commons.lang3.Range.hashCode()```

Also, it fails with the same error for
- ```org.apache.commons.lang3.exception.ExceptionUtils.getStackTrace(java.lang.Throwable)```

Randoops exits with:

Throwable thrown while handling command: java.lang.Error: accessibleObject is null for org.apache.commons.lang3.exception.ExceptionUtils.getStackTrace(java.lang.Throwable), typically due to predicates: randoop.reflection.VisibilityPredicate$PublicVisibilityPredicate@ ....

Is any hashCode() omitted by default due to nondeterminism? 

Thank you,

**Comment by mernst** [comment]
I'm sorry you are having trouble.
We would like to help you, but cannot do so from your fragmentary report.
Can you please provide a reproducible test case that others can run to get the same output you did?
The instructions were in the text box you typed your report into, and are in the Randoop manual.

**Comment by andrewhabib** [comment]
Hi,

Thank you for your reply.

Actually, the problem is persistent and reproducible using any hashCode() method as entry in --methodlist argument.

The following shell script reproduce the behavior I encounter with hashCode()

```
echo "java.util.TreeSet.hashCode()" > methods.txt
java -cp $(RANDOOP_JAR) randoop.main.Main gentests --testclass=java.util.TreeSet --output-limit=100 --methodlist methods.txt
```

My guess is that this is due to the special cases excluded in DefaultReflectionPredicate.

If that is true, may be Randoop should handle these cases more gracefully; i.e., when --methodlist contains some of the special cases that should be excluded, a warning is better than throwing an exception and failing?

**Comment by mernst** [comment]
Thanks for the reproduction; that is very helpful.
I have opened pull request #645 so that Randoop prints a message rather than erring when the user specifies to test an untestable method.  This implements your suggestion.
Thanks again!

**Comment by andrewhabib** [comment]
Awesome! 

Thank you so much for the prompt action.

**Comment by andrewhabib** [comment]
I tested it and confirm it works as expected! 
Thanks again!
