### ISSUE TITLE
Failed to instantiate heap; 3000M requested

### ISSUE THREAD

**Issue by PYangDizzle** [randoop/randoop#675]
Randoop version 4.2.1
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 8.0.5.20 - pwi3280sr5fp20-20180802_01(SR5 FP20))
IBM J9 VM (build 2.9, JRE 1.8.0 Windows 10 x86-32-Bit 20180731_393394 (JIT enabled, AOT enabled)
OpenJ9   - bd23af8
OMR      - ca1411c
IBM      - 98805ca)
JCL - 20180719_01 based on Oracle jdk8u181-b12
Windos 10 Enterprise

I ran randoop in Eclipse-based IDE.
It failed with following message:
---
...
Regression test output:
Regression test count: 56
Writing regression JUnit tests...
GenTests.writeTestFiles threw an exception
randoop.main.RandoopBug: Did not find "There\s+(?:was|were)\s+(\d+)\s+failure(?:s|):" in execution of RegressionTest0
status=Status 1 (timedOut=false) for command "java -ea -Xmx3000m -XX:+HeapDumpOnOutOfMemoryError -classpath .....ommitted... org.junit.runner.JUnitCore RegressionTest0", stdout=""
, stderr lines=3
Standard output:

... end of standard output.
...
---

I directly executed the failed command because "stderr lines=3"
 java -ea -Xmx3000m -XX:+HeapDumpOnOutOfMemoryError -classpath .....ommitted... org.junit.runner.JUnitCore RegressionTest0,
It failed with more information
JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate heap; 3000M requested
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

Status.toString() prints stderr only if it has less than 2 lines.
The original output should print the content of stderr since it exists.

**Comment by mernst** [comment]
Thanks for the bug report, and I'm sorry it was harder than it should have been to diagnose the problem.

You raised two issues:
 * Failed to instantiate heap.  This is a Java problem:  you need to run on a computer where more memory is available.  For example, close other large programs before running Randoop.
 * Status.toString() prints stderr only if it has less than 2 lines.
   I have fixed this in commit 6b9ca4ef0640c95fd1ec9bf6d6505c78ba8ce976.

Let us know if you have other problems.

**Comment by PYangDizzle** [comment]
@mernst Thanks for the quick response.
I changed GenInputsAbstract.jvm_max_memory to a lower value in main()
public static void main(String[] args) {
		GenInputsAbstract.jvm_max_memory = "1024M";
		Main.main(new String[] {"gentests", ...
}

Could you can answer some questions?

1. Why is "3000M" hard coded? 
2. Can JUnit be called directly? (i.e. new JUnitCore().runMain(randoopSystem, args))
The current way JUnit is run creates a separate heap. If I have fixed amount, A, of memory that I can use for Randoop, Randoop would only be able to use A-3000M of memory to generate tests.
If JUnit is called directly, the heap would be shared. + We would be able to step into JUnit's code without doing attach-debugger-shenanigans.

**Comment by mernst** [comment]
I'm happy to answer questions.

1. 3000m is not hard-coded.  You can control this value using the [--jvm-max-memory](https://randoop.github.io/randoop/manual/index.html#option:jvm-max-memory) command-line option.

2. Running JUnit directly is desirable for both of the reasons you suggested.  However, doing so loses isolation between the processes.  Here are some potential problems:
   * If a test has side effects, those side effects are persisted -- to other tests and to Randoop itself.
   * If a test calls `System.exit()`, Randoop will exit.

**Comment by PYangDizzle** [comment]
@mernst Makes sense. I could argue different hacks to reset between tests or isolate the tests, but the only truly guaranteed isolation is only by separate processes.
However, I can't stop thinking that it's awkward to have 2 sequential resource-intensive processes not reuse or share a heap.
Since that's the case, it won't hurt to have the option to separate test generation from test execution.
Then the user would do "genTest" then "execTest" with the maximum resource available for both.
Does this make sense?

**Comment by mernst** [comment]
Randoop's test generation phase may create tests that do not pass.  For example, Randoop might generate this test:
```
  Object x = new Object();
  assert x.toString.equals("java.lang.Object;@18f6bc30");
```
Randoop executes its tests to ensure that they pass, and doesn't output the ones that fail.
This would need to be integrated into the "execTest" component.

I think it would be valuable to have an option to run JUnit directly, as you suggested.
Separating the two components would also be valuable.
(Both of these would be controlled by an option and off by default.)

Would you be willing to submit a pull request?

**Comment by PYangDizzle** [comment]
@mernst Sure, I'll try it out.

One more question. Does "omit-classes" work in 4.2.1?  '-' vs '_'
```
@Option("Do not test classes that match regular expression <string>")
/*   85 */   public static List<Pattern> omit_classes = new ArrayList<>();
```
--omit-classes=regex [+]. 

Also, I see that the code to populate _omit_classses_ was added only 7 days ago in GenTests.java

**Comment by mernst** [comment]
`--omit-classes` works in the master branch.  It does not work in 4.2.1 (see https://github.com/randoop/randoop/issues/599).

**Comment by PYangDizzle** [comment]
@mernst
Okay, i was only asking because --omit-classes was in the manual.
