### ISSUE TITLE
Float.NaN and Double.NaN comparison still fails due to using deprecated methods, org.junit.Assert.assertEquals(double, double) 

### ISSUE THREAD

**Issue by terminiter** [randoop/randoop#70]
The current fix for #13, #61 seems still incomplete under Junit-4.10 or later version, the reason was caused by using deprecated method assertEquals(double, double), which always return false even given the same value for comparison.
e.g.
```java
assertEquals(Double.NaN, Double.NaN); // return false
```
or
```java
assertEquals(1.1, 1.1);  // return false
```

A quick fix would update the depracated method ``` assertEquals(double, double) ``` to  ``` assertEquals(double expected, double actual, double epsilon)``` as follows:

Update ```randoop.PrimValue.java```

```diff
103a104
>     
109c110
<       b.append(");");
---
>         b.append(", 0);");
111a113
>     
```

BTW, this problem was found when generating tests for Apache Math 3.2.

Thanks,
Lei Ma

**Comment by mernst** [comment]
Thank you for the bug report and the fix!  I appreciate it.
I have pushed your change, as commit 92bfbab.
