### ISSUE TITLE
Incorrect separator for resource name

### ISSUE THREAD

**Issue by PYangDizzle** [randoop/randoop#726]
According to the following link the name of the resource is platform-independent and is always path/to/resource.

https://docs.oracle.com/javase/8/docs/technotes/guides/lang/resources.html
- The name of a resource is independent of the Java implementation; in particular, the path separator is always a slash (/). 
- The name of a resource is a "/"-separated sequence of identifiers.

However in Randoop 4.2.1/replacecall-4.2.1/randoop.instrument.ReplacementFileReader, the resource name is platform-dependent, using File.separatorChar which is '/' for Unix and "\\" for Windows.
```
private static void addReplacementsForClassOrPackage(HashMap<MethodSignature, MethodSignature> replacementMap, String original, String replacement) throws ReplacementException, IOException, ClassNotFoundException {
/* 243 */     String replacementClassPath = replacement.replace('.', File.separatorChar) + ".class";
/* 244 */     URL resource = ClassLoader.getSystemResource(replacementClassPath);
```
This causes an exception and the agent will fail to run.
It seems like Replace Agent never worked for Windows. Maybe other jars should be checked too.

As a fix, I think the separator should be hard coded to '/' or find a constant that's already defined somewhere in the jdk.

**Comment by mernst** [comment]
Thanks for noticing this!  You are right that we don't test on Windows. :-/

I looked through all uses of File.separatorChar and found 3 that needed to be changed.  The others look fine.

**Comment by PYangDizzle** [comment]
When do you think the fix will be packaged into the jar?

**Comment by mernst** [comment]
You can build the jar file by running `./gradlew assemble`.
If you are asking when a new Randoop release will be made and uploaded to Maven Central, I can do that if it is blocking you.

**Comment by PYangDizzle** [comment]
I'll just wait for the next release
