### ISSUE TITLE
Unable to load class "PetClinicApplication" due to exception: java.lang.ClassNotFoundException: PetClinicApplicationWill explore 0 out of 1 classes

### ISSUE THREAD

**Issue by jinuprakash** [randoop/randoop#752]
Hi Team,
![image](https://user-images.githubusercontent.com/62925600/77990415-e4157700-733e-11ea-88f3-31bd4f8c399e.png)
 

this is the issue Imfacing at the moment. Could you please help me here ASAP :(

**Comment by mernst** [comment]
I'm sorry you are having trouble.  We would like to help you, but we cannot do so from this incomplete bug report.  Can you please provide all the details that were requested in the [issue template](https://github.com/randoop/randoop/issues/new) and the [bug reporting section of the manual](https://randoop.github.io/randoop/manual/#bug-reporting)?  This will enable us to reproduce the problem, fix it, and verify the fix.  Thanks!

**Comment by jinuprakash** [comment]
Hi mernst
This issue was resolved. However, I do have a question :
How can we configure randoop to a maven project

**Comment by mernst** [comment]
I'm sorry, but I don't understand your question.  Are you building on Randoop?  Do you want to upload Randoop to a repository such as Maven Central?  Do you want to create a Maven task that runs Randoop?  Something else?

If you could give more complete information, we can help you.

Note that this issue is not the right place to talk about general Maven integration.  Please close this issue if it is resolved.  (Please also say what you did to resolve the problem, to help other users who may read this issue in the future.  Thanks!)

**Comment by jinuprakash** [comment]
Hi,
Sorry if Im not being clear.
I wanted to generate some test cases for a maven project. I'm not able to
find any documentation that guide me for this purpose.

I hope you can help me with this.

Thanks,
Jinu Prakash

**Comment by mernst** [comment]
As I stated in my previous comment, please don't have other, unrelated conversations in a thread.  It's confusing.  You can ask on the mailing list or open a new issue if it is a bug.

Can you please close this issue if the "java.lang.ClassNotFoundException" problem is resolved, and explain how you resolved it?

**Comment by jinuprakash** [comment]
Sorry its been resolved

**Comment by jinuprakash** [comment]
Hi Michael,

I'm sorry that I started to discuss off topic subject related to the
thread.
But if possible could you please let me know how can I get randoop to
generate regression suites for a sample maven project.

Thanks,
Jinu Prakash

**Comment by mernst** [comment]
Jinu-

Please, *please* do not discuss off-topic subjects.  I don't want to have to ban you for repeated violations.  You can send email or open another issue.
