### ISSUE TITLE
Compilation issue in TS: assertNull(String,String) is called without the class and package name

### ISSUE THREAD

**Issue by Ahmedfir** [randoop/randoop#756]
In the outputted test suite, I am facing a compilation issue related to a non imported assertion method. i.e:
`java.io.File file19 = new File("");
 assertNull("file19.getParent() == null", file19.getParent());`

I have also noticed that this is only happening with String type null assertions and not with other object ones. i.e. `org.junit.Assert.assertNull(modelResolver49);`

Please let me know if you need further details or if I can help fixing this error. 

Thank you for your time and support.

PS: the used Randoop version is 4.2.2.

**Comment by mernst** [comment]
I think you are asking for all uses of `assertNull` to be fully-qualified (as some of them are already).  Thanks for pointing out this discrepancy; I appreciate the bug report.
I have corrected this in https://github.com/randoop/randoop/commit/508c972b59feec317c92262d220cb23795d455c7.
