### ISSUE TITLE
Cannot find the Java compiler. Check that classpath includes tools.jar

### ISSUE THREAD

**Issue by kpuneetgoyal** [randoop/randoop#766]
I am trying to use 4.2.3 version.
I have JAVA_HOME installed and hence mvn clean install is working.

I tried running command
java -classpath %RANDOOP_JAR% randoop.main.Main gentests --testclass=sunlife.egistration.controller.RegistrationIdentificationController

Error:
Randoop for Java version 4.2.3.

Cannot find the Java compiler. Check that classpath includes tools.jar.
Classpath:
/C:/Xfunction/randoop-4.2.3/randoop-all-4.2.3.jar

**Comment by kpuneetgoyal** [comment]
C:\Users\j515>echo %JAVA_HOME%
**C:\eclipse47\jdk180_172**

C:\Users\j515>echo %PATH%
C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Lotus\Notes;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files (x86)\Personal Communications\;C:\Program Files (x86)\IBM\Trace Facility\;C:\Program Files\Common Files\IBM\MQM\bin64;C:\Program Files\Common Files\IBM\MQM\bin;C:\Program Files\Common Files\IBM\MQM\tools\c\samples\bin64;C:\Program Files\Common Files\IBM\MQM\tools\c\samples\bin;C:\Users\j515\AppData\Local\Microsoft\WindowsApps;C:\Users\j515\Downloads\apache-maven-3.6.2\bin;C:\Users\j515\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\j515\AppData\Roaming\npm;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\cmd;C:\Xfunction\Zookeper\bin;**C:\eclipse47\jdk180_172\bin;C:\eclipse47\jdk180_172\lib\tools.jar;**

**Comment by mernst** [comment]
The message tells you the exact problem:

> Cannot find the Java compiler. Check that classpath includes tools.jar.
> Classpath:
> /C:/Xfunction/randoop-4.2.3/randoop-all-4.2.3.jar

Your second message shows that you added `tools.jar` to your path (where the operating system looks for executables), but that is different than the classpath (where Java looks for classes).
