### ISSUE TITLE
Randoop: Error while reading class names file myclasses: myclasses (The system cannot find the file specified)

### ISSUE THREAD

**Issue by LakshmiNagandla** [randoop/randoop#780]
When we are trying to execute myclasses.txt file (file consisted more than one class).  We are getting below error message 

Error while reading class names file myclasses: myclasses (The system cannot find the file specified)

Command which I used: 

D:\RandoopAlgoritham\randoop-4.2.3\randoop-4.2.3\bin>java -classpath D:\RandoopAlgoritham\randoop-4.2.3\randoop-4.2.3\bin;D:\RandoopAlgoritham\randoop-4.2.3\randoop-4.2.3\randoop-all-4.2.3.jar randoop.main.Main gentests --classlist=myclasses

**Comment by mernst** [comment]
If you read the error message, you can solve your problem.  In the future, please read the error mesasge.

The error message says that file `myclasses` was not found.
If you want Randoop to use `myclasses.txt`, then specify that file.  The files `myclasses` and `myclasses.txt` are different files.
