### ISSUE TITLE
Unable  to debug randoop source code

### ISSUE THREAD

**Issue by ykj1414** [randoop/randoop#786]
randoop-4.2.4
jdk1.8
MacOS 10.14.6
I want to debug randoop source code for further development, but a filesystem error occurred like this:

**Throwable thrown while handling command: java.lang.IllegalArgumentException: Path component should be '/'
java.lang.IllegalArgumentException: Path component should be '/'**

If I just include jar file in new project and parse args to main class, it works well and generates tests.I checked the code and found that its the filesystem identifying the directoryURI as a ZipFileSystem makes the code work.however using a jar file would be difficult for me to debug and change the code.

So is there any way I can do to fix this problem?

**Comment by mernst** [comment]
I'm sorry you are having trouble.  We would like to help you, but we cannot do so from this incomplete bug report.  Can you please provide all the details that were requested in the [issue template](https://github.com/randoop/randoop/issues/new) and the [bug reporting section of the manual](https://randoop.github.io/randoop/manual/#bug-reporting)?  This will enable us to reproduce the problem, fix it, and verify the fix.  Thanks!
