### ISSUE TITLE
Randoop failed with specification file.

### ISSUE THREAD

**Issue by ykj1414** [randoop/randoop#791]
Randoop Version: 
   randoop-4.2.4
Java Version:
  Java version "11" 2018-09-25
  Java(TM) SE Runtime Environment 18.9 (build 11+28)
  Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11+28, mixed mode)

Operating System Version:
  MacOS 10.14.6 

Complete Commands：
  java -ea -cp .:./randoop-all-4.2.4.jar:./localtest/test/S_128.class randoop.main.Main gentests --testclass=localtest.test.S_128 --specifications=/Users/ying/JavaProjects/LeetCode/src/specification.json --output-limit=60

Command output:

Randoop for Java version 4.2.4.

Will try to generate tests for 1 classes.
Removing localtest.test.S_128 from the classes under test due to problem extracting operations:
randoop.condition.RandoopSpecificationError: Condition method did not compile:
4:46: 需要';'

Class Declaration:
package localtest.test;

public class RandoopExpressionClass0 {
  public static boolean signature_S_128_int[]_S_128_Integer_Integer(localtest.test.S_128 receiver, int[] nums, localtest.test.S_128 s_128, java.lang.Integer test01, java.lang.Integer test02) throws Throwable {
    return test01 > 0;
  }
}
: Compilation failed
	at randoop.condition.ExecutableBooleanExpression.createMethod(ExecutableBooleanExpression.java:224)
	at randoop.condition.ExecutableBooleanExpression.<init>(ExecutableBooleanExpression.java:88)
	at randoop.condition.SpecificationTranslator.create(SpecificationTranslator.java:374)
	at randoop.condition.SpecificationTranslator.getGuardExpressions(SpecificationTranslator.java:271)
	at randoop.condition.SpecificationTranslator.createExecutableSpecification(SpecificationTranslator.java:253)
	at randoop.condition.SpecificationCollection.getExecutableSpecification(SpecificationCollection.java:319)
	at randoop.reflection.OperationExtractor.visit(OperationExtractor.java:462)
	at randoop.reflection.ReflectionManager.applyTo(ReflectionManager.java:284)
	at randoop.reflection.ReflectionManager.apply(ReflectionManager.java:134)
	at randoop.reflection.OperationExtractor.operations(OperationExtractor.java:214)
	at randoop.reflection.OperationModel.addOperationsFromClasses(OperationModel.java:679)
	at randoop.reflection.OperationModel.createModel(OperationModel.java:173)
	at randoop.main.GenTests.handle(GenTests.java:311)
	at randoop.main.Main.nonStaticMain(Main.java:70)
	at randoop.main.Main.main(Main.java:30)
Caused by: randoop.compile.SequenceCompilerException: Compilation failed
	at randoop.compile.SequenceCompiler.compile(SequenceCompiler.java:135)
	at randoop.compile.SequenceCompiler.compileAndLoad(SequenceCompiler.java:183)
	at randoop.condition.ExecutableBooleanExpression.createMethod(ExecutableBooleanExpression.java:221)
	... 14 more

You provided no methods to test, so no tests for them can be generated.
Model with hashcode 711197015:
  classTypes = [java.lang.Object]
  inputTypes = [int[], java.lang.Boolean, java.lang.Integer, java.lang.Long, java.lang.Object, java.lang.String, localtest.test.S_128]
  coveredClassesGoal = []
  classLiteralMap = {}
  annotatedTestValues = []
  contracts = ContractSet[size=12]
    arity 1: [randoop.contract.EqualsReflexive@5d8bafa9, randoop.contract.EqualsToNullRetFalse@576f63f6, randoop.contract.EqualsReturnsNormally@2dca0d64, randoop.contract.CompareToReflexive@f80945f, randoop.contract.SizeToArrayLength@ff684e1]
    arity 2: [randoop.contract.EqualsSymmetric@23aa363a, randoop.contract.EqualsHashcode@5ef6ae06, randoop.contract.CompareToAntiSymmetric@55dfebeb, randoop.contract.CompareToEquals@6e35bc3d]
    arity 3: [randoop.contract.EqualsTransitive@1cdc4c27, randoop.contract.CompareToSubs@77b14724, randoop.contract.CompareToTransitive@5d9b7a8a]

  omitMethods = [^org.apache.commons.math3.analysis.differentiation., ^org.apache.commons.math3.analysis.integration., \bensuresCapacity\b, ^\Qcom.google.common.collect.Iterators.cycle(, ^\Qorg.apache.commons.math4.genetics.GeneticAlgorithm.getRandomGenerator()\E$, ^\Qorg.apache.commons.math4.util.FastMath.random()\E$, ^\Qjava.util.Date.<init>()\E$, ^\Qorg.joda.time.DateTime.now()\E$, ^\Qorg.joda.time.LocalDate.<init>\E$, ^\Qnew org.joda.time.Partial.<init>()\E$, ^\Qjava.io.File.list()\E$, ^\Qjava.io.File.list(java.io.FilenameFilter)\E$, ^\Qjava.io.File.listFiles()\E$, ^\Qjava.io.File.listFiles(java.io.FileFilter)\E$, ^\Qjava.io.File.listFiles(java.io.FilenameFilter)\E$, ^\Qjava.io.File.listRoots()\E$, ^\Qjava.lang.Class.getSigners()\E$, ^\Qjava.lang.Object.hashCode()\E$, ^\Qjava.lang.String.hashCode()\E$, ^\Qjava.lang.System.clearProperty(java.lang.String)\E$, ^\Qjava.lang.System.console()\E$, ^\Qjava.lang.System.currentTimeMillis()\E$, ^\Qjava.lang.System.getProperties()\E$, ^\Qjava.lang.System.getProperty(java.lang.String)\E$, ^\Qjava.lang.System.getProperty(java.lang.String, java.lang.String)\E$, ^\Qjava.lang.System.getSecurityManager()\E$, ^\Qjava.lang.System.getenv()\E$, ^\Qjava.lang.System.getenv(java.lang.String)\E$, ^\Qjava.lang.System.identityHashCode(java.lang.Object)\E$, ^\Qjava.lang.System.inheritedChannel()\E$, ^\Qjava.lang.System.mapLibraryName(java.lang.String)\E$, ^\Qjava.lang.System.nanoTime()\E$, ^\Qjava.lang.System.setProperty(java.lang.String, java.lang.String)\E$, ^\Qjava.lang.reflect.Method.hashCode()\E$, ^\Qjava.text.BreakIterator.getAvailableLocales()\E$, ^\Qjava.util.AbstractList.hashCode()\E$, ^\Qjava.util.AbstractSet.hashCode()\E$, ^\Qjava.util.Arrays.deepHashCode(java.lang.Object[])\E$, ^\Qjava.util.Arrays.hashCode(boolean[])\E$, ^\Qjava.util.Arrays.hashCode(byte[])\E$, ^\Qjava.util.Arrays.hashCode(char[])\E$, ^\Qjava.util.Arrays.hashCode(double[])\E$, ^\Qjava.util.Arrays.hashCode(float[])\E$, ^\Qjava.util.Arrays.hashCode(int[])\E$, ^\Qjava.util.Arrays.hashCode(java.lang.Object[])\E$, ^\Qjava.util.Arrays.hashCode(long[])\E$, ^\Qjava.util.Arrays.hashCode(short[])\E$, ^\Qjava.util.Collection.hashCode()\E$, ^\Qjava.util.Collections.shuffle(java.util.List)\E$, ^\Qjava.util.Comparator.compare(java.lang.Object, java.lang.Object)\E$, ^\Qjava.util.List.hashCode()\E$, ^\Qjava.util.Random.<init>()\E$, ^\Qjava.util.Set.hashCode()\E$]
Operations: 
  java.lang.Object.<init> : () -> java.lang.Object

There are no methods for Randoop to test.  See diagnostics above.  Exiting.

Here are my specification file and class file 
[mytest.zip](https://github.com/randoop/randoop/files/4986285/mytest.zip)

**Comment by mernst** [comment]
Thanks for the bug report -- we appreciate it.  (And my apologies for the bug.)

I have committed a change that fixes your test case.  Please let us know if you encounter further problems.
