### ISSUE TITLE
ClassNotFoundException when class is directly pointed to

### ISSUE THREAD

**Issue by jmath675** [randoop/randoop#801]
I'm using Randoop 4.2.4 and jdk-11 on Windows 10. 

I ran:

"C:\Documents\jdk-11\bin\java.exe" -classpath C:\Documents\testingProj\src;C:\Documents\randoop-4.2.4\randoop.jar randoop.main.Main gentests --testclass=testingProj.test

-----------------------------------------------------------------------------------------

This is my output:

Randoop for Java version 4.2.4.
Unable to load class "testingProj.test" due to exception: java.lang.ClassNotFoundException: testingProj.test
Will try to generate tests for 0 out of 1 classes.
You provided no methods to test, so no tests for them can be generated.
Model with hashcode 988800485:
  classTypes = [java.lang.Object]
  inputTypes = []
  coveredClassesGoal = []
  classLiteralMap = {}
  annotatedTestValues = []
  contracts = ContractSet[size=12]
    arity 1: [randoop.contract.EqualsReflexive@2f7c2f4f, randoop.contract.EqualsToNullRetFalse@6af93788, randoop.contract.EqualsReturnsNormally@ef9296d, randoop.contract.CompareToReflexive@36c88a32, randoop.contract.SizeToArrayLength@7880cdf3]
    arity 2: [randoop.contract.EqualsSymmetric@5be6e01c, randoop.contract.EqualsHashcode@1c93084c, randoop.contract.CompareToAntiSymmetric@6ef888f6, randoop.contract.CompareToEquals@10e92f8f]
    arity 3: [randoop.contract.EqualsTransitive@7ce3cb8e, randoop.contract.CompareToSubs@78b66d36, randoop.contract.CompareToTransitive@5223e5ee]

  omitMethods = [^org.apache.commons.math3.analysis.differentiation., ^org.apache.commons.math3.analysis.integration., \bensuresCapacity\b, ^\Qcom.google.common.collect.Iterators.cycle(, ^\Qorg.apache.commons.math4.genetics.GeneticAlgorithm.getRandomGenerator()\E$, ^\Qorg.apache.commons.math4.util.FastMath.random()\E$, ^\Qjava.util.Date.<init>()\E$, ^\Qorg.joda.time.DateTime.now()\E$, ^\Qorg.joda.time.LocalDate.<init>\E$, ^\Qnew org.joda.time.Partial.<init>()\E$, ^\Qjava.io.File.list()\E$, ^\Qjava.io.File.list(java.io.FilenameFilter)\E$, ^\Qjava.io.File.listFiles()\E$, ^\Qjava.io.File.listFiles(java.io.FileFilter)\E$, ^\Qjava.io.File.listFiles(java.io.FilenameFilter)\E$, ^\Qjava.io.File.listRoots()\E$, ^\Qjava.lang.Class.getSigners()\E$, ^\Qjava.lang.Object.hashCode()\E$, ^\Qjava.lang.String.hashCode()\E$, ^\Qjava.lang.System.clearProperty(java.lang.String)\E$, ^\Qjava.lang.System.console()\E$, ^\Qjava.lang.System.currentTimeMillis()\E$, ^\Qjava.lang.System.getProperties()\E$, ^\Qjava.lang.System.getProperty(java.lang.String)\E$, ^\Qjava.lang.System.getProperty(java.lang.String, java.lang.String)\E$, ^\Qjava.lang.System.getSecurityManager()\E$, ^\Qjava.lang.System.getenv()\E$, ^\Qjava.lang.System.getenv(java.lang.String)\E$, ^\Qjava.lang.System.identityHashCode(java.lang.Object)\E$, ^\Qjava.lang.System.inheritedChannel()\E$, ^\Qjava.lang.System.mapLibraryName(java.lang.String)\E$, ^\Qjava.lang.System.nanoTime()\E$, ^\Qjava.lang.System.setProperty(java.lang.String, java.lang.String)\E$, ^\Qjava.lang.reflect.Method.hashCode()\E$, ^\Qjava.text.BreakIterator.getAvailableLocales()\E$, ^\Qjava.util.AbstractList.hashCode()\E$, ^\Qjava.util.AbstractSet.hashCode()\E$, ^\Qjava.util.Arrays.deepHashCode(java.lang.Object[])\E$, ^\Qjava.util.Arrays.hashCode(boolean[])\E$, ^\Qjava.util.Arrays.hashCode(byte[])\E$, ^\Qjava.util.Arrays.hashCode(char[])\E$, ^\Qjava.util.Arrays.hashCode(double[])\E$, ^\Qjava.util.Arrays.hashCode(float[])\E$, ^\Qjava.util.Arrays.hashCode(int[])\E$, ^\Qjava.util.Arrays.hashCode(java.lang.Object[])\E$, ^\Qjava.util.Arrays.hashCode(long[])\E$, ^\Qjava.util.Arrays.hashCode(short[])\E$, ^\Qjava.util.Collection.hashCode()\E$, ^\Qjava.util.Collections.shuffle(java.util.List)\E$, ^\Qjava.util.Comparator.compare(java.lang.Object, java.lang.Object)\E$, ^\Qjava.util.List.hashCode()\E$, ^\Qjava.util.Random.<init>()\E$, ^\Qjava.util.Set.hashCode()\E$]
Operations:
  java.lang.Object.<init> : () -> java.lang.Object

There are no methods for Randoop to test.  See diagnostics above.  Exiting.

-----------------------------------------------------------------------------------------

I expected Randoop to create test cases for the simple boolean method inside of the test.java class, but Randoop will not recognize any class in Java projects that I've tried. 

Files that are used by the commands you ran.
[testingProj.zip](https://github.com/randoop/randoop/files/5190357/testingProj.zip)

**Comment by mernst** [comment]
I'm sorry you are having trouble.

The problem is that you have not put your class testingProj.test on the classpath.
You need to augment the `-classpath` command-line argument.

All the examples in the Randoop Manual show the classes under test on the classpath.  Note that thee manual's examples are for Unix including Linux and Mac.  Windows uses `;` instead of `:` as the classpath separator.

Does that solve your problem?

**Comment by jmath675** [comment]
I understand the -classpath method, but Randoop seems to be having a problem with imports inside of my project. is there a way to get it to read the .classpath file and see all imports from other classes?

**Comment by mernst** [comment]
Sorry, I don't know what you mean by "Randoop seems to be having a problem with imports inside of my project".  If you could provide a minimal reproducible test case, we could take a look at it.

Regarding the `.classpath` file, that is supported by some IDEs but isn't an official part of Java.  You could convert it into the form required by Java's `-classpath` command-line argument.  If you wanted to create a Randoop pull request that supports the `.classpath` file, we would welcome that.
