### ISSUE TITLE
Unable to load class "ConfigureJob.java" due to exception: java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by orpheus84** [randoop/randoop#809]
I'm having a problem getting randoop to generate test classes. I am using version 4.2.4 and after inserting my .class file inside a folder I launched randoop with this command: java -classpath C: \ Users \ Administrator \ Desktop \ randoop-4.2.4 \ bin; C: \ Users \ Administrator \ Desktop \ randoop-4.2.4 \ randoop-all-4.2.4.jar randoop.main.Main gentests --testclass = ConfigureJob The ConfigureJob.class file is present in the path C: \ Users \ Administrator \ Desktop \ randoop-4.2.4 \ bin The mistake that gets me out is

Randoop for Java version 4.2.4.
Unable to load class "ConfigureJob" due to exception: java.lang.ClassNotFoundException: ConfigureJob
Will try to generate tests for 0 out of 1 classes.
You provided no methods to test, so no tests for them can be generated.
Model with hashcode 1273765644:
  classTypes = [java.lang.Object]
  inputTypes = []
  coveredClassesGoal = []
  classLiteralMap = {}
  annotatedTestValues = []
  contracts = ContractSet[size=12]
    arity 1: [randoop.contract.EqualsReflexive@29ca901e, randoop.contract.EqualsToNullRetFalse@5649fd9b, randoop.contract.EqualsReturnsNormally@6adede5, randoop.contract.CompareToReflexive@2d928643, randoop.contract.SizeToArrayLength@5025a98f]
    arity 2: [randoop.contract.EqualsSymmetric@49993335, randoop.contract.EqualsHashcode@20322d26, randoop.contract.CompareToAntiSymmetric@192b07fd, randoop.contract.CompareToEquals@64bfbc86]
    arity 3: [randoop.contract.EqualsTransitive@64bf3bbf, randoop.contract.CompareToSubs@55d56113, randoop.contract.CompareToTransitive@148080bb]

  omitMethods = [^org.apache.commons.math3.analysis.differentiation., ^org.apache.commons.math3.analysis.integration., \bensuresCapacity\b, ^\Qcom.google.common.collect.Iterators.cycle(, ^\Qorg.apache.commons.math4.genetics.GeneticAlgorithm.getRandomGenerator()\E$, ^\Qorg.apache.commons.math4.util.FastMath.random()\E$, ^\Qjava.util.Date.<init>()\E$, ^\Qorg.joda.time.DateTime.now()\E$, ^\Qorg.joda.time.LocalDate.<init>\E$, ^\Qnew org.joda.time.Partial.<init>()\E$, ^\Qjava.io.File.list()\E$, ^\Qjava.io.File.list(java.io.FilenameFilter)\E$, ^\Qjava.io.File.listFiles()\E$, ^\Qjava.io.File.listFiles(java.io.FileFilter)\E$, ^\Qjava.io.File.listFiles(java.io.FilenameFilter)\E$, ^\Qjava.io.File.listRoots()\E$, ^\Qjava.lang.Class.getSigners()\E$, ^\Qjava.lang.Object.hashCode()\E$, ^\Qjava.lang.String.hashCode()\E$, ^\Qjava.lang.System.clearProperty(java.lang.String)\E$, ^\Qjava.lang.System.console()\E$, ^\Qjava.lang.System.currentTimeMillis()\E$, ^\Qjava.lang.System.getProperties()\E$, ^\Qjava.lang.System.getProperty(java.lang.String)\E$, ^\Qjava.lang.System.getProperty(java.lang.String, java.lang.String)\E$, ^\Qjava.lang.System.getSecurityManager()\E$, ^\Qjava.lang.System.getenv()\E$, ^\Qjava.lang.System.getenv(java.lang.String)\E$, ^\Qjava.lang.System.identityHashCode(java.lang.Object)\E$, ^\Qjava.lang.System.inheritedChannel()\E$, ^\Qjava.lang.System.mapLibraryName(java.lang.String)\E$, ^\Qjava.lang.System.nanoTime()\E$, ^\Qjava.lang.System.setProperty(java.lang.String, java.lang.String)\E$, ^\Qjava.lang.reflect.Method.hashCode()\E$, ^\Qjava.text.BreakIterator.getAvailableLocales()\E$, ^\Qjava.util.AbstractList.hashCode()\E$, ^\Qjava.util.AbstractSet.hashCode()\E$, ^\Qjava.util.Arrays.deepHashCode(java.lang.Object[])\E$, ^\Qjava.util.Arrays.hashCode(boolean[])\E$, ^\Qjava.util.Arrays.hashCode(byte[])\E$, ^\Qjava.util.Arrays.hashCode(char[])\E$, ^\Qjava.util.Arrays.hashCode(double[])\E$, ^\Qjava.util.Arrays.hashCode(float[])\E$, ^\Qjava.util.Arrays.hashCode(int[])\E$, ^\Qjava.util.Arrays.hashCode(java.lang.Object[])\E$, ^\Qjava.util.Arrays.hashCode(long[])\E$, ^\Qjava.util.Arrays.hashCode(short[])\E$, ^\Qjava.util.Collection.hashCode()\E$, ^\Qjava.util.Collections.shuffle(java.util.List)\E$, ^\Qjava.util.Comparator.compare(java.lang.Object, java.lang.Object)\E$, ^\Qjava.util.List.hashCode()\E$, ^\Qjava.util.Random.<init>()\E$, ^\Qjava.util.Set.hashCode()\E$]
Operations:
  java.lang.Object.<init> : () -> java.lang.Object

There are no methods for Randoop to test.  See diagnostics above.  Exiting.

Attach the .class file that i use (it in zip package because i can't attach .class file) for my test and the zip package of randoop 

[randoop-4.2.4.zip](https://github.com/randoop/randoop/files/5285214/randoop-4.2.4.zip)

[ConfigureJob.zip](https://github.com/randoop/randoop/files/5285221/ConfigureJob.zip)

Thank you very much

Best Regards

**Comment by mernst** [comment]
I'm sorry you are having trouble.

`java.lang.ClassNotFoundException` indicates that the classes under test are not in the classpath.  The most likely case is that you have not included the path to these classes.  Another possible cause is that you did not supply the classpath to Randoop properly.  I can't tell which of these causes (or some other) is the case for you.

We would like to help you.  Unfortunately, this bug report is not reproducible.  Can you please provide more complete information?

> after inserting my .class file inside a folder 

What .class file?  What exact folder?

The command you have given cannot be what you typed, because it contains extra spaces around the backslashes.  Please cut-and-paste the exact command, and say where you ran it.

You mentioned a `randoop-4.2.4 \ bin` directory, but the `randoop.zip` file that you provided does not have one.

Can you provide the exact commands that you ran, starting with downloading Randoop (and building it, if you did that), and culminating in the error, in a way that we can cut-and-paste into a shell in order to reproduce your problem?  Thanks!

**Comment by orpheus84** [comment]
Hi,

thank you for answering me.

[randoop-4.2.4.zip](https://github.com/randoop/randoop/files/5286438/randoop-4.2.4.zip)

In the zip there is exactly all folder when i put the class file and tha randoop.jar that i have execute. The command that i ran is

java -classpath C:\Users\Administrator\Desktop\randoop-4.2.4\bin;C:\Users\Administrator\Desktop\randoop-4.2.4\randoop-all-4.2.4.jar randoop.main.Main gentests --testclass=ConfigureJob

Obiviously tha base path C:\Users\Administrator\Desktop rapresent where my randoop folder is on Desktop. 

To ran the java command I position myself inside the folder where the java executable jdk 8 is present, in my case is C:\Program Files\Java\jdk1.8.0_181\bin

So the entire command line on my prompt in windows is 

C:\Program Files\Java\jdk1.8.0_181\bin>java.exe -classpath C:\Users\Administrator\Desktop\randoop-4.2.4\bin;C:\Users\Administrator\Desktop\randoop-4.2.4\randoop-all-4.2.4.jar randoop.main.Main gentests --testclass=ConfigureJob

Thanks

Best Regards

**Comment by mernst** [comment]
Thank you for the additional information.  That permitted me to reproduce your problem.

Here are three problems:

1. You passed `--testclass=ConfigureJob`, but there is no class whose fully-qualified name is `ConfigureJob`.  Your command line should have used `--testclass=it.exprivia.enelx.evos.scheduler.job.ConfigureJob`.

2. The `ConfigureJob.class` file should not be directly within `bin`.  Rather, it should be in a subdirectory `it\exprivia\enelx\evos\scheduler\job\ConfigureJob` of bin (or of some other directory that is on the classpath).

3. The `ConfigureJob` class depends on `org.quartz.ScheduleBuilder` which also needs to be available on the classpath.

I hope this helps.

**Comment by orpheus84** [comment]
Hi ,

now work!! Great!
Thanks 

I noticed that if the class contains references to other dependencies I am forced to enter the classpath of these other dependencies which maybe belong to other applications. Is there a way to integrate randoop into eclipse and make sure that the dependencies are automatically recalled without entering the classpath of each application where the dependency is contained?

Thanks

Best Regards

**Comment by mernst** [comment]
You need to provide Randoop the full classpath, which contains all the dependencies.  This is exactly the same as when compiling or running a program.  It probably works to just obtain the classpath that Eclipse uses.  Maybe this is in `.classpath`, or maybe it is elsewhere.  I am not an Eclipse user, though.
