### ISSUE TITLE
Unable to run Randoop : problem with paths and folders

### ISSUE THREAD

**Issue by gillesfabre34** [randoop/randoop#845]
Hello,

I have a very simple problem, but even with the tutorial and with the troubleshooting page, I don't find the solution.

I just want to execute Randoop on a project, and I have an error with the path or the classpath, I think.

I still have the error `No class found for type name "example.ExampleClass"
Unable to load class "example.ExampleClass" due to exception: java.lang.ClassNotFoundException`, and I don't understand where exactly I make a mistake.

I launch this command-line in the root project's folder :
```
java -Xmx3000m -classpath ./randoop-4.2.5/randoop-all-4.2.5.jar randoop.main.Main gentests --testclass=tutorial.Stack --output-limit=100
```
the file `randoop-all-4.2.5.jar` is in the folder `./randoop-4.2.5` and the class `Stack` is in the folder `./src/main/java/tutorial`.

when I run `echo $CLASSPATH`, I have the output `./src/main`. It's probably here that something is wrong, but I don't know what.

Any help would be great ! :)

My OS is Mac OS Big Sur, and my java version is 11

**Comment by mernst** [comment]
I'm sorry you are having trouble.

**Regarding the first part of your bug report:**

Where is the class `example.ExampleClass` defined?  You didn't give me a way to reproduce the problem.

This looks like a Java problem, not a Randoop problem.

This command line:
```
java -Xmx3000m -classpath ./randoop-4.2.5/randoop-all-4.2.5.jar ...
```

says to Java: "All the classes can be found in `./randoop-4.2.5/randoop-all-4.2.5.jar`."

As noted in the ["Running Randoop" section of the manual](https://randoop.github.io/randoop/manual/#running_randoop), a typical command line is:

```
java -Xmx3000m -classpath myclasspath:${RANDOOP_JAR} randoop.main.Main gentests --testclass=java.util.TreeSet --output-limit=100
```

Note the "myclasspath" part.  If you add a location that contains a definition of `example.ExampleClass`, that should fix the problem.


**Regarding the second part of your bug report:**

This looks similar to the first part.  You will need to put the location of file `tutorial/Stack.class` on the classpath.

You didn't show the value of `$CLASSPATH`, so again I cannot reproduce the problem.  If $CLASSPATH contains `src/main`, then maybe it should instead contain `src/main/java`, if that is the directory that contains `tutorial/Stack.class`.  But, if you pass the `-classpath` command-line argument explicitly, I would expect that your `$CLASSPATH` is ignored.

If this doesn't help, could you please provide a reproducible example?  Then we can give you more definitive help.

**Comment by gillesfabre34** [comment]
Hi,

At first, thanks a lot for your quick response. You was right, there was a problem with the "myclasspath" : I didn't understand well what I needed to do with it.

So now, I can execute correctly Randoop by using the command-line below : 

```
 java -Xmx3000m -classpath ./target/classes:./randoop-4.2.5/randoop-all-4.2.5.jar randoop.main.Main gentests --testclass=tutorial.Stack --output-limit=100
```

Thanks again !
:)
