### ISSUE TITLE
Generated test by Randoop (using option --junit-reflection-allowed=false) won't compile

### ISSUE THREAD

**Issue by hsanchez** [randoop/randoop#85]
FYI, @mernst

@bjkeller  

I used the `--junit-reflection-allowed=false` option as indicated. Randoop generated a test class containing a `main` method. Unfortunately,  the test methods could not be executed since the generated test class is throwing many `';' expected` errors:

```
__randoop_0000/RegressionTestDriver.java:6: error: ';' expected
RegressionTest0 t0= new RegressionTest0()
                                         ^
__randoop_0000/RegressionTestDriver.java:8: error: ';' expected
      t0.test01()
                 ^
__randoop_0000/RegressionTestDriver.java:14: error: ';' expected
      t0.test02()
                 ^

... and many more errors of this type (see attached files for additional information)
```
By looking at the generate test class (See attached file), it seems that there is a bug in Randoop's `main method` generation. The  `--junit-reflection-allowed=false` option produces a test class that won't compile.

Attached to this issue, you will find 3 files:

1. a file containing the executed commands: [randoop-cmds.txt](https://github.com/randoop/randoop/files/143417/randoop-cmds.txt)

2. a log file: [log.txt](https://github.com/randoop/randoop/files/143413/log.txt)
3. the test class generated by Randoop:
[RegressionTestDriver.java.txt](https://github.com/randoop/randoop/files/143418/RegressionTestDriver.java.txt)

Let me know if you need to more information.

**Comment by bjkeller** [comment]
Huascar,  
Thanks for the report, and I apologize for the bug. I will get a fix to this out ASAP.
Ben
