### ISSUE TITLE
Generated tests should not require the Randoop Java agent

### ISSUE THREAD

**Issue by GoogleCodeExporter** [randoop/randoop#9]
```
The Randoop Java agent

  -javaagent:$(randoop)/randoop_agent.jar=--map_calls=map_calls.txt

is a way of avoiding calls to system routines.

The JUnit tests that are output by Randoop need to be run with that same
javaagent.  It would be better if Randoop's output was self-contained.  To
do so, Randoop should record which tests have their execution detoured by
the javaagent, and should never output such tests.

```

Original issue reported on code.google.com by `michael.ernst@gmail.com` on 15 Jul 2010 at 11:55

**Comment by mernst** [comment]
The easiest way to do this would be to for the agent's instrumentation to output when it gets called, then Randoop to read that output to decide which tests not to output.

This would be controlled by a switch.

I'm closing this old feature request for now.
