### ISSUE TITLE
Reading JML Specification

### ISSUE THREAD

**Issue by Amirfarhad-Nilizadeh** [randoop/randoop#933]
Hi,

Can Randoop directly read JML specifications? For example, for the following programs:

https://github.com/Amirfarhad-Nilizadeh/Java-JML

**Comment by mernst** [comment]
No.  Per manual section ["Specifying expected code behavior"](https://randoop.github.io/randoop/manual/#specifying-behavior), Randoop reads specifications in JSON format.  It does not read Java files and parse the JML comments within them.  That parsing task is best done by the JML toolset.

You could write a translator from JML comments to JSON format.  If you wished to contribute such a tool to Randoop, we would welcome a pull request.  Thanks in advance!

**Comment by Amirfarhad-Nilizadeh** [comment]
Thank you for your response. I am interested to work in converting JML specifications to JSON. But I am working on some other projects currently. May in 2022 I can work on it.

I have two more questions. (1) I added preconditions to generate tests for a simple program with one argument. It generates more valid tests, but it still generates some invalid input. Program and JSON files are attached. Can you please look at them? (2) How should define an array with a primitive type in the "parameterTypes"? I tried "parameterTypes": [  "int[]" ], but it cannot be compiled.

[Problem.zip](https://github.com/randoop/randoop/files/6633781/Problem.zip)

Please let me know if I should open two new issues and ask these questions.

Thanks in advance for your help and time.

**Comment by mernst** [comment]
Your bug report does not say what command to run to reproduce the problem.  I can guess, but that will consume time and I might guess wrong.  Could you please open a new issue and provide all the information requested in the [manual](https://randoop.github.io/randoop/manual/#bug-reporting) and in the issue tracker template?  Then we can investigate and fix the problem for you.  Thanks!
