### ISSUE TITLE
Not checking precondition correctly

### ISSUE THREAD

**Issue by Amirfarhad-Nilizadeh** [randoop/randoop#934]
Hi,

I added preconditions to generate tests for a simple program with only one argument (argument value should be in the range of 0 to 20). It generates more valid tests by using JSON contract than its default setting, but it still generates invalid input like -1, 'a', and '#'. Program and JSON and all generated tests are attached. I used Randoop version 4.2.6, and the operating system is Ubuntu 18.4.

java -ea -classpath /home/amirfarhad/Desktop/ProgramAnalysis/codes/Randoop/Factorial/bin:/home/amirfarhad/Desktop/ProgramAnalysis/Tools/randoop-4.2.6/randoop-all-4.2.6.jar randoop.main.Main gentests --testclass=org.Factorial --specifications=specification.JSON

[Factorial.zip](https://github.com/randoop/randoop/files/6634724/Factorial.zip)

**Comment by mernst** [comment]
The JSON file you provided is malformed.

1. It isn't valid JSON.  You can use your editor's JSON mode/plugin, or use a tool like https://jsonlint.com/, to ensure that you are writing legal JSON.
2. It doesn't conform to the example at https://randoop.github.io/randoop/manual/net_connection_spec.json.  (The example at https://randoop.github.io/randoop/api/randoop/condition/specification/OperationSpecification.html is buggy and I will [fix it](https://github.com/randoop/randoop/pull/937).  Thanks for this bug report, which pointed that out.)

Here is a corrected JSON file:

```json
[
    {
	"operation": {
	    "classname": "org.Factorial",
	    "name": "factorial",
	    "parameterTypes": [
		"int"
	    ]
	},
	"identifiers": {
	    "parameters": [
		"n"
            ]
	},
	"pre": [
	    {
		"description": "the ipnut must be positive",
		"guard": {
		    "description": "the code must be positive",
      		    "condition": "n >= 0"
		}
	    },
	    {
		"description": "the signalValue must be positive",
		"guard": {
		    "description": "the ipnut must be less than 21",
		    "condition": "n < 21"
		}
	    }
	]  
    }
]
```

With this file, I cannot reproduce your problem.

**Comment by Amirfarhad-Nilizadeh** [comment]
Thank you so much for your help.

**Comment by mernst** [comment]
No problem.  I'm glad we determined the problem and fixed the faulty documentation.
