### ISSUE TITLE
Running Randoop-generated tests independently

### ISSUE THREAD

**Issue by mernst** [randoop/randoop#97]
One can use `--testsperfile=1` to put one Randoop test per file, but there is still just one test driver created that runs them all.  It would be nice to have a command-line argument to create a separate test driver per test file, and then a user can run the Randoop-generated tests completely independently of one another.

**Comment by bjkeller** [comment]
This is when `--junit-reflection-allowed=false`, correct?

**Comment by mernst** [comment]
I'm closing this because it doesn't seem critical.
If it's important to some user, we can re-open it.
