### ISSUE TITLE
Support for a version of java greater than 11

### ISSUE THREAD

**Issue by fduminy** [randoop/randoop#993]
Are there any plan to support recent version of java (greater than java 11) ?
What should be done to achieve this goal ?

**Comment by mernst** [comment]
Yes, this is an important goal.
@markro49 is currently working on Java 17 support.

**Comment by mernst** [comment]
As of version 4.3.0 (released January 31, 2022), Randoop supports Java 8, 11, and 17, which is all LTS versions of Java.
